package com.yuguo.net.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.sf.json.JSONArray;

import com.yuguo.net.common.config.ibatis.AbstractExample;
import com.yuguo.net.utils.ConstantUtils;

public class MallGoodsExample extends AbstractExample{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public MallGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    protected MallGoodsExample(MallGoodsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected List<Map<String, Object>> criteriaWithAssembledValue;

        /**
         * <p>由代码生成器创建的构造函数。</p>
         */
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
            criteriaWithAssembledValue = new ArrayList<Map<String, Object>>();
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0
                || criteriaWithAssembledValue.size() > 0;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithAssembledValue() {
            return criteriaWithAssembledValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Map<String, Object> getAssembledConditionMap(String condition, String value) {
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            return map;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        protected void addCriterion(List<? extends Object> values, String conditionEnd) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("values", values);
            map.put("conditionEnd", conditionEnd);
            criteriaWithAssembledValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdIsNull() {
            addCriterion("mallGoods.GOODS_ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdIsNotNull() {
            addCriterion("mallGoods.GOODS_ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("mallGoods.GOODS_ID =", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_ID <>", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_ID >", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_ID >=", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("mallGoods.GOODS_ID <", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_ID <=", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdLike(String value) {
            addCriterion("mallGoods.GOODS_ID like", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("mallGoods.GOODS_ID not like", value, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("mallGoods.GOODS_ID in", values, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_ID not in", values, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_ID between", value1, value2, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_ID not between", value1, value2, "goodsId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdIsNull() {
            addCriterion("mallGoods.ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdIsNotNull() {
            addCriterion("mallGoods.ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdEqualTo(Long value) {
            addCriterion("mallGoods.ID =", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("mallGoods.ID <>", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdGreaterThan(Long value) {
            addCriterion("mallGoods.ID >", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mallGoods.ID >=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdLessThan(Long value) {
            addCriterion("mallGoods.ID <", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("mallGoods.ID <=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdIn(List<Long> values) {
            addCriterion("mallGoods.ID in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("mallGoods.ID not in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("mallGoods.ID between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("mallGoods.ID not between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleIsNull() {
            addCriterion("mallGoods.GOODS_TITLE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleIsNotNull() {
            addCriterion("mallGoods.GOODS_TITLE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleEqualTo(String value) {
            addCriterion("mallGoods.GOODS_TITLE =", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_TITLE <>", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_TITLE >", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_TITLE >=", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleLessThan(String value) {
            addCriterion("mallGoods.GOODS_TITLE <", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_TITLE <=", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleLike(String value) {
            addCriterion("mallGoods.GOODS_TITLE like", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleNotLike(String value) {
            addCriterion("mallGoods.GOODS_TITLE not like", value, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleIn(List<String> values) {
            addCriterion("mallGoods.GOODS_TITLE in", values, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_TITLE not in", values, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_TITLE between", value1, value2, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsTitleNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_TITLE not between", value1, value2, "goodsTitle");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassIsNull() {
            addCriterion("mallGoods.GOODS_CLASS is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassIsNotNull() {
            addCriterion("mallGoods.GOODS_CLASS is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassEqualTo(String value) {
            addCriterion("mallGoods.GOODS_CLASS =", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_CLASS <>", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_CLASS >", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_CLASS >=", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassLessThan(String value) {
            addCriterion("mallGoods.GOODS_CLASS <", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_CLASS <=", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassLike(String value) {
            addCriterion("mallGoods.GOODS_CLASS like", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassNotLike(String value) {
            addCriterion("mallGoods.GOODS_CLASS not like", value, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassIn(List<String> values) {
            addCriterion("mallGoods.GOODS_CLASS in", values, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_CLASS not in", values, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_CLASS between", value1, value2, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsClassNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_CLASS not between", value1, value2, "goodsClass");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceIsNull() {
            addCriterion("mallGoods.PROMOTION_PRICE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceIsNotNull() {
            addCriterion("mallGoods.PROMOTION_PRICE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceEqualTo(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE =", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceNotEqualTo(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE <>", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceGreaterThan(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE >", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE >=", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceLessThan(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE <", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE <=", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceLike(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE like", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceNotLike(String value) {
            addCriterion("mallGoods.PROMOTION_PRICE not like", value, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceIn(List<String> values) {
            addCriterion("mallGoods.PROMOTION_PRICE in", values, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceNotIn(List<String> values) {
            addCriterion("mallGoods.PROMOTION_PRICE not in", values, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceBetween(String value1, String value2) {
            addCriterion("mallGoods.PROMOTION_PRICE between", value1, value2, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andPromotionPriceNotBetween(String value1, String value2) {
            addCriterion("mallGoods.PROMOTION_PRICE not between", value1, value2, "promotionPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceIsNull() {
            addCriterion("mallGoods.GOODS_PRICE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("mallGoods.GOODS_PRICE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceEqualTo(String value) {
            addCriterion("mallGoods.GOODS_PRICE =", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_PRICE <>", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_PRICE >", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_PRICE >=", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceLessThan(String value) {
            addCriterion("mallGoods.GOODS_PRICE <", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_PRICE <=", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceLike(String value) {
            addCriterion("mallGoods.GOODS_PRICE like", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceNotLike(String value) {
            addCriterion("mallGoods.GOODS_PRICE not like", value, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceIn(List<String> values) {
            addCriterion("mallGoods.GOODS_PRICE in", values, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_PRICE not in", values, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_PRICE between", value1, value2, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsPriceNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_PRICE not between", value1, value2, "goodsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesIsNull() {
            addCriterion("mallGoods.GOODS_IMAGES is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesIsNotNull() {
            addCriterion("mallGoods.GOODS_IMAGES is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesEqualTo(String value) {
            addCriterion("mallGoods.GOODS_IMAGES =", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_IMAGES <>", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_IMAGES >", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_IMAGES >=", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesLessThan(String value) {
            addCriterion("mallGoods.GOODS_IMAGES <", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_IMAGES <=", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesLike(String value) {
            addCriterion("mallGoods.GOODS_IMAGES like", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesNotLike(String value) {
            addCriterion("mallGoods.GOODS_IMAGES not like", value, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesIn(List<String> values) {
            addCriterion("mallGoods.GOODS_IMAGES in", values, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_IMAGES not in", values, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_IMAGES between", value1, value2, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsImagesNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_IMAGES not between", value1, value2, "goodsImages");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceIsNull() {
            addCriterion("mallGoods.APPS_PRICE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceIsNotNull() {
            addCriterion("mallGoods.APPS_PRICE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceEqualTo(String value) {
            addCriterion("mallGoods.APPS_PRICE =", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceNotEqualTo(String value) {
            addCriterion("mallGoods.APPS_PRICE <>", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceGreaterThan(String value) {
            addCriterion("mallGoods.APPS_PRICE >", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.APPS_PRICE >=", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceLessThan(String value) {
            addCriterion("mallGoods.APPS_PRICE <", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.APPS_PRICE <=", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceLike(String value) {
            addCriterion("mallGoods.APPS_PRICE like", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceNotLike(String value) {
            addCriterion("mallGoods.APPS_PRICE not like", value, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceIn(List<String> values) {
            addCriterion("mallGoods.APPS_PRICE in", values, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceNotIn(List<String> values) {
            addCriterion("mallGoods.APPS_PRICE not in", values, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceBetween(String value1, String value2) {
            addCriterion("mallGoods.APPS_PRICE between", value1, value2, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andAppsPriceNotBetween(String value1, String value2) {
            addCriterion("mallGoods.APPS_PRICE not between", value1, value2, "appsPrice");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthIsNull() {
            addCriterion("mallGoods.LOGISTICS_WEIGTH is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthIsNotNull() {
            addCriterion("mallGoods.LOGISTICS_WEIGTH is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthEqualTo(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH =", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthNotEqualTo(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH <>", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthGreaterThan(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH >", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH >=", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthLessThan(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH <", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH <=", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthLike(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH like", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthNotLike(String value) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH not like", value, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthIn(List<String> values) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH in", values, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthNotIn(List<String> values) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH not in", values, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthBetween(String value1, String value2) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH between", value1, value2, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andLogisticsWeigthNotBetween(String value1, String value2) {
            addCriterion("mallGoods.LOGISTICS_WEIGTH not between", value1, value2, "logisticsWeigth");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationIsNull() {
            addCriterion("mallGoods.GOODS_LOCATION is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationIsNotNull() {
            addCriterion("mallGoods.GOODS_LOCATION is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationEqualTo(String value) {
            addCriterion("mallGoods.GOODS_LOCATION =", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_LOCATION <>", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_LOCATION >", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_LOCATION >=", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationLessThan(String value) {
            addCriterion("mallGoods.GOODS_LOCATION <", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_LOCATION <=", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationLike(String value) {
            addCriterion("mallGoods.GOODS_LOCATION like", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationNotLike(String value) {
            addCriterion("mallGoods.GOODS_LOCATION not like", value, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationIn(List<String> values) {
            addCriterion("mallGoods.GOODS_LOCATION in", values, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_LOCATION not in", values, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_LOCATION between", value1, value2, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsLocationNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_LOCATION not between", value1, value2, "goodsLocation");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeIsNull() {
            addCriterion("mallGoods.GOODS_BARCODE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeIsNotNull() {
            addCriterion("mallGoods.GOODS_BARCODE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeEqualTo(String value) {
            addCriterion("mallGoods.GOODS_BARCODE =", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeNotEqualTo(String value) {
            addCriterion("mallGoods.GOODS_BARCODE <>", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeGreaterThan(String value) {
            addCriterion("mallGoods.GOODS_BARCODE >", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_BARCODE >=", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeLessThan(String value) {
            addCriterion("mallGoods.GOODS_BARCODE <", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.GOODS_BARCODE <=", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeLike(String value) {
            addCriterion("mallGoods.GOODS_BARCODE like", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeNotLike(String value) {
            addCriterion("mallGoods.GOODS_BARCODE not like", value, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeIn(List<String> values) {
            addCriterion("mallGoods.GOODS_BARCODE in", values, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeNotIn(List<String> values) {
            addCriterion("mallGoods.GOODS_BARCODE not in", values, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_BARCODE between", value1, value2, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andGoodsBarcodeNotBetween(String value1, String value2) {
            addCriterion("mallGoods.GOODS_BARCODE not between", value1, value2, "goodsBarcode");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeIsNull() {
            addCriterion("mallGoods.CREATE_TIME is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeIsNotNull() {
            addCriterion("mallGoods.CREATE_TIME is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("mallGoods.CREATE_TIME =", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("mallGoods.CREATE_TIME <>", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("mallGoods.CREATE_TIME >", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mallGoods.CREATE_TIME >=", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("mallGoods.CREATE_TIME <", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("mallGoods.CREATE_TIME <=", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("mallGoods.CREATE_TIME in", values, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("mallGoods.CREATE_TIME not in", values, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("mallGoods.CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("mallGoods.CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayIsNull() {
            addCriterion("mallGoods.IS_PUTAWAY is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayIsNotNull() {
            addCriterion("mallGoods.IS_PUTAWAY is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayEqualTo(String value) {
            addCriterion("mallGoods.IS_PUTAWAY =", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayNotEqualTo(String value) {
            addCriterion("mallGoods.IS_PUTAWAY <>", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayGreaterThan(String value) {
            addCriterion("mallGoods.IS_PUTAWAY >", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayGreaterThanOrEqualTo(String value) {
            addCriterion("mallGoods.IS_PUTAWAY >=", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayLessThan(String value) {
            addCriterion("mallGoods.IS_PUTAWAY <", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayLessThanOrEqualTo(String value) {
            addCriterion("mallGoods.IS_PUTAWAY <=", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayLike(String value) {
            addCriterion("mallGoods.IS_PUTAWAY like", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayNotLike(String value) {
            addCriterion("mallGoods.IS_PUTAWAY not like", value, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayIn(List<String> values) {
            addCriterion("mallGoods.IS_PUTAWAY in", values, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayNotIn(List<String> values) {
            addCriterion("mallGoods.IS_PUTAWAY not in", values, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayBetween(String value1, String value2) {
            addCriterion("mallGoods.IS_PUTAWAY between", value1, value2, "isPutaway");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        public Criteria andIsPutawayNotBetween(String value1, String value2) {
            addCriterion("mallGoods.IS_PUTAWAY not between", value1, value2, "isPutaway");
            return this;
        }
        
        public Criteria andGoodsStatusEqualTo(String value) {
            addCriterion("mallGoodsInfo.GOODS_STATUS =", value, "goodsStatus");
            return this;
        }
        
        public Criteria andGoodsStatusEqualTo1(String value) {
            addCriterion("mallGoodsInfo.GOODS_STATUS = goodsStatus");
            return this;
        }
        
        public Criteria andAuditStatusEqualTo(String value) {
            addCriterion("mallGoodsInfo.AUDIT_STATUS =", value, "auditStatus");
            return this;
        }
        //传入商家id,获取此商家的商品
        public Criteria andMerchantNumEqualTo(String value){
        	addCriterion("mallGoodsInfo.MERCHANT_NUM=",value,"merchantNum");
        	return this;
        }
        
        
        /*商品搜索*/
        public Criteria andSearchCondition(String columnName,String value,String option) {
        	if(columnName.equals("GOODS_PRICE") || columnName.equals("APPS_PRICE") || columnName.equals("PROMOTION_PRICE")){
        		addCriterion("convert(mallGoods."+columnName+", DECIMAL)"+" "+option+" "+value+" " );
        	}else if(columnName.equals("STORE_NUM") || columnName.equals("UPLOAD_STATUS") || columnName.equals("MERCHANT_NUM")){
        		if("未上传".equals(value) || "待上传".equals(value)){
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.NOT_UPLOAD+"' " );
        		}else if("已上传".equals(value)){
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.IS_UPLOAD+"' " );
        		}else{
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+value+"' " );
        		}
        	}else{
        		addCriterion("mallGoods."+columnName+" "+option+" '"+value+"' " );
        	}
        	return this;
        }
        
        /*商品搜索开始于*/
        public Criteria andSearchBeginWith(String columnName,String value,String option) {
        	if(columnName.equals("UPLOAD_STATUS")){
        		if("未上传".contains(value) || "待上传".contains(value)){
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.NOT_UPLOAD+"%' " );
        		}else{
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.IS_UPLOAD+"%' " );
        		}
        	}else{
        		addCriterion("mallGoods."+columnName+" "+option+" '"+value+"%' " );
        	}
        	return this;
        }
        
        /*商品搜索结束于*/
        public Criteria andSearchEndWith(String columnName,String value,String option) {
        	if(columnName.equals("UPLOAD_STATUS")){
        		if("未上传".contains(value) || "待上传".contains(value)){
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.NOT_UPLOAD+"%' " );
        		}else{
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.IS_UPLOAD+"%' " );
        		}
        	}else{
        		addCriterion("mallGoods."+columnName+" "+option+" '%"+value+"' " );
        	}
        	return this;
        }
        
        /*商品搜索包含*/
        public Criteria andSearchContain(String columnName,String value,String option) {
        	if(columnName.equals("UPLOAD_STATUS")){
        		if("未上传".contains(value) || "待上传".contains(value)){
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.NOT_UPLOAD+"%' " );
        		}else{
        			addCriterion("mallGoodsInfo."+columnName+" "+option+" '"+ConstantUtils.IS_UPLOAD+"%' " );
        		}
        	}else{
        		addCriterion("mallGoods."+columnName+" "+option+" '%"+value+"%' " );
        	}
        	return this;
        }
        
        /*OR查询*/
        public Criteria orRules(String groupOp,JSONArray rules) {
        	String strRule="(";
        	for(int i = 0 ; i < rules.size(); i++){
				String field = (String)rules.getJSONObject(i).get("field");  // 参数字段
				String option = (String)rules.getJSONObject(i).get("op");    // 参数条件  bw 开始于  bn 不开始与   ew 结束于  en不结束于  cn包含于  nc不包含于
				String data = (String)rules.getJSONObject(i).get("data");    // 查询内容
				
				String tableName = getMallGoodsOrInfo(field);
				
				if(i!=0){
					strRule += " "+groupOp+" ";
				}
				
				if(field.equals("UPLOAD_STATUS")){
					if("未上传".contains(data) || "待更新".contains(data)){
	        			data = ConstantUtils.NOT_UPLOAD;
	        		}else{
	        			data = ConstantUtils.IS_UPLOAD;
	        		}
				}
				
				if(field.equals("AUDIT_STATUS")){ //审核状态1审核通过 0 未通过 2未提交审核 3待审核',
					if("审核通过".contains(data)){
						data = ConstantUtils.AUDIT_PASS;
					}else if("未通过".contains(data)){
						data = ConstantUtils.AUDIT_NOT_PASS;
					}else if("待审核".contains(data)){
						data = ConstantUtils.IS_SUBMIT_AUDIT;
					}else if("未提交".contains(data)){
						data = ConstantUtils.NOT_SUBMIT_AUDIT;
					}
				}
				
				if(field.equals("GOODS_PRICE") || field.equals("APPS_PRICE") || field.equals("PROMOTION_PRICE")){
					strRule += "convert("+tableName+"."+field+", DECIMAL) ";
				}else{
					strRule += " "+tableName +"."+field;
				}
				
				if("eq".equals(option)){// bw 开始于  bn 不开始与   ew 结束于  en不结束于  cn包含于  nc不包含于
					option = "=";
					strRule+=" "+option+" '"+data+"' ";
				}else if("ne".equals(option)){
					option = "!=";
					strRule+=" "+option+" '"+data+"' ";
				}else if("lt".equals(option)){
					option = "<";
					strRule+=" "+option+" '"+data+"' ";
				}else if("le".equals(option)){
					option = "<=";
					strRule+=" "+option+" '"+data+"' ";
				}else if("gt".equals(option)){
					option = ">";
					strRule+=" "+option+" '"+data+"' ";
				}else if("ge".equals(option)){
					option = ">=";
					strRule+=" "+option+" '"+data+"' ";
				}else if("bw".equals(option)){
					option = "like";
					strRule+=" "+option+" '"+data+"%' ";
				}else if("bn".equals(option)){
					option = "not like";
					strRule+=" "+option+" '"+data+"%' ";
				}else if("ew".equals(option)){
					option = "like";
					strRule+=" "+option+" '%"+data+"' ";
				}else if("en".equals(option)){
					option = "not like";
					strRule+=" "+option+" '%"+data+"' ";
				}else if("cn".equals(option)){
					option = "like";
					strRule+=" "+option+" '%"+data+"%' ";
				}else if("nc".equals(option)){
					option = "not like";
					strRule+=" "+option+" '%"+data+"%' ";
				}
			}
        	strRule+=")";
        	addCriterion(strRule);
        	return this;		
        }
        
        public String getMallGoodsOrInfo(String columnName){
        	String returnStr = "";
        	if(columnName.equals("UPLOAD_STATUS") || columnName.equals("STORE_NUM")  || columnName.equals("AUDIT_STATUS") ){
        		returnStr="mallGoodsInfo";
        	}else{
        		returnStr="mallGoods";
        	}
        	return returnStr;
        }
        
    }
}