package com.yuguo.net.model;

import java.io.Serializable;
import java.util.Date;

public class MallGoods implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_TITLE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsTitle;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_CLASS
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsClass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.PROMOTION_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String promotionPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_IMAGES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsImages;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.APPS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String appsPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.LOGISTICS_WEIGTH
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String logisticsWeigth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_LOCATION
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsLocation;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_BARCODE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String goodsBarcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.CREATE_TIME
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.IS_PUTAWAY
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private String isPutaway;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.GOODS_DESC
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private byte[] goodsDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods.APPS_DES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private byte[] appsDes;


    private Integer storeNum;

    private Long infoId;
    
    private String uploadStatus;
    
    private String goodsStatus;
    
    private String attributeName;
    
    private String isSubGoods;
    
    private String merchantNum;
    
    private String activityId;

    private String auditStatus;

    private String unpassReason;

    private String adId;
    
    private byte[] standardParam;
    
    private String classAttribute;
    
    private String packingList;
    
    private String classFeature;
    
    private String goodsBrand;
    
	public String getGoodsBrand() {
		return goodsBrand;
	}

	public void setGoodsBrand(String goodsBrand) {
		this.goodsBrand = goodsBrand;
	}

	public String getGoodsStatus() {
		return goodsStatus;
	}

	public void setGoodsStatus(String goodsStatus) {
		this.goodsStatus = goodsStatus;
	}

	public String getAttributeName() {
		return attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getIsSubGoods() {
		return isSubGoods;
	}

	public void setIsSubGoods(String isSubGoods) {
		this.isSubGoods = isSubGoods;
	}

	public String getUploadStatus() {
		return uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	public Long getInfoId() {
		return infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public Integer getStoreNum() {
		return storeNum;
	}

	public void setStoreNum(Integer storeNum) {
		this.storeNum = storeNum;
	}

	
	public String getActivityId() {
		return activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public String getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}

	public String getUnpassReason() {
		return unpassReason;
	}

	public void setUnpassReason(String unpassReason) {
		this.unpassReason = unpassReason;
	}

	public String getAdId() {
		return adId;
	}

	public void setAdId(String adId) {
		this.adId = adId;
	}

	public byte[] getStandardParam() {
		return standardParam;
	}

	public void setStandardParam(byte[] standardParam) {
		this.standardParam = standardParam;
	}

	public String getClassAttribute() {
		return classAttribute;
	}

	public void setClassAttribute(String classAttribute) {
		this.classAttribute = classAttribute;
	}

	
	public String getPackingList() {
		return packingList;
	}

	public void setPackingList(String packingList) {
		this.packingList = packingList;
	}

	
	public String getClassFeature() {
		return classFeature;
	}

	public void setClassFeature(String classFeature) {
		this.classFeature = classFeature;
	}
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 构造函数
     */
    public MallGoods() {
        //Auto-generated Constructor stub
    }

    /**
     * 构造函数
     * @param goodsId goodsId
     * @param id id
     */
    public MallGoods(String goodsId, Long id) {
        this.goodsId = goodsId;
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_ID
     *
     * @return the value of t_mall_goods.GOODS_ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_ID
     *
     * @param goodsId the value for t_mall_goods.GOODS_ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.ID
     *
     * @return the value of t_mall_goods.ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.ID
     *
     * @param id the value for t_mall_goods.ID
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_TITLE
     *
     * @return the value of t_mall_goods.GOODS_TITLE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_TITLE
     *
     * @param goodsTitle the value for t_mall_goods.GOODS_TITLE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_CLASS
     *
     * @return the value of t_mall_goods.GOODS_CLASS
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsClass() {
        return goodsClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_CLASS
     *
     * @param goodsClass the value for t_mall_goods.GOODS_CLASS
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsClass(String goodsClass) {
        this.goodsClass = goodsClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.PROMOTION_PRICE
     *
     * @return the value of t_mall_goods.PROMOTION_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.PROMOTION_PRICE
     *
     * @param promotionPrice the value for t_mall_goods.PROMOTION_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setPromotionPrice(String promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_PRICE
     *
     * @return the value of t_mall_goods.GOODS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_PRICE
     *
     * @param goodsPrice the value for t_mall_goods.GOODS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_IMAGES
     *
     * @return the value of t_mall_goods.GOODS_IMAGES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsImages() {
        return goodsImages;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_IMAGES
     *
     * @param goodsImages the value for t_mall_goods.GOODS_IMAGES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsImages(String goodsImages) {
        this.goodsImages = goodsImages;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.APPS_PRICE
     *
     * @return the value of t_mall_goods.APPS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getAppsPrice() {
        return appsPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.APPS_PRICE
     *
     * @param appsPrice the value for t_mall_goods.APPS_PRICE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setAppsPrice(String appsPrice) {
        this.appsPrice = appsPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.LOGISTICS_WEIGTH
     *
     * @return the value of t_mall_goods.LOGISTICS_WEIGTH
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getLogisticsWeigth() {
        return logisticsWeigth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.LOGISTICS_WEIGTH
     *
     * @param logisticsWeigth the value for t_mall_goods.LOGISTICS_WEIGTH
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setLogisticsWeigth(String logisticsWeigth) {
        this.logisticsWeigth = logisticsWeigth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_LOCATION
     *
     * @return the value of t_mall_goods.GOODS_LOCATION
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsLocation() {
        return goodsLocation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_LOCATION
     *
     * @param goodsLocation the value for t_mall_goods.GOODS_LOCATION
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsLocation(String goodsLocation) {
        this.goodsLocation = goodsLocation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_BARCODE
     *
     * @return the value of t_mall_goods.GOODS_BARCODE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getGoodsBarcode() {
        return goodsBarcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_BARCODE
     *
     * @param goodsBarcode the value for t_mall_goods.GOODS_BARCODE
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsBarcode(String goodsBarcode) {
        this.goodsBarcode = goodsBarcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.CREATE_TIME
     *
     * @return the value of t_mall_goods.CREATE_TIME
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.CREATE_TIME
     *
     * @param createTime the value for t_mall_goods.CREATE_TIME
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.IS_PUTAWAY
     *
     * @return the value of t_mall_goods.IS_PUTAWAY
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public String getIsPutaway() {
        return isPutaway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.IS_PUTAWAY
     *
     * @param isPutaway the value for t_mall_goods.IS_PUTAWAY
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setIsPutaway(String isPutaway) {
        this.isPutaway = isPutaway;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.GOODS_DESC
     *
     * @return the value of t_mall_goods.GOODS_DESC
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public byte[] getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.GOODS_DESC
     *
     * @param goodsDesc the value for t_mall_goods.GOODS_DESC
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setGoodsDesc(byte[] goodsDesc) {
        this.goodsDesc = goodsDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods.APPS_DES
     *
     * @return the value of t_mall_goods.APPS_DES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public byte[] getAppsDes() {
        return appsDes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods.APPS_DES
     *
     * @param appsDes the value for t_mall_goods.APPS_DES
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void setAppsDes(byte[] appsDes) {
        this.appsDes = appsDes;
    }

    public String getMerchantNum() {
		return merchantNum;
	}

	public void setMerchantNum(String merchantNum) {
		this.merchantNum = merchantNum;
	}
	
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof MallGoods)) {
            return false;
        }
        MallGoods other = (MallGoods) that;
        return this.getGoodsId() == null ? other == null : this.getGoodsId().equals(other.getGoodsId())
            && this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getGoodsTitle() == null ? other == null : this.getGoodsTitle().equals(other.getGoodsTitle())
            && this.getGoodsClass() == null ? other == null : this.getGoodsClass().equals(other.getGoodsClass())
            && this.getPromotionPrice() == null ? other == null : this.getPromotionPrice().equals(other.getPromotionPrice())
            && this.getGoodsPrice() == null ? other == null : this.getGoodsPrice().equals(other.getGoodsPrice())
            && this.getGoodsImages() == null ? other == null : this.getGoodsImages().equals(other.getGoodsImages())
            && this.getAppsPrice() == null ? other == null : this.getAppsPrice().equals(other.getAppsPrice())
            && this.getLogisticsWeigth() == null ? other == null : this.getLogisticsWeigth().equals(other.getLogisticsWeigth())
            && this.getGoodsLocation() == null ? other == null : this.getGoodsLocation().equals(other.getGoodsLocation())
            && this.getGoodsBarcode() == null ? other == null : this.getGoodsBarcode().equals(other.getGoodsBarcode())
            && this.getCreateTime() == null ? other == null : this.getCreateTime().equals(other.getCreateTime())
            && this.getIsPutaway() == null ? other == null : this.getIsPutaway().equals(other.getIsPutaway())
            && this.getGoodsDesc() == null ? other == null : this.getGoodsDesc().equals(other.getGoodsDesc())
            && this.getAppsDes() == null ? other == null : this.getAppsDes().equals(other.getAppsDes());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGoodsId() != null) {
            hash *= getGoodsId().hashCode();
        }
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getGoodsTitle() != null) {
            hash *= getGoodsTitle().hashCode();
        }
        if (getGoodsClass() != null) {
            hash *= getGoodsClass().hashCode();
        }
        if (getPromotionPrice() != null) {
            hash *= getPromotionPrice().hashCode();
        }
        if (getGoodsPrice() != null) {
            hash *= getGoodsPrice().hashCode();
        }
        if (getGoodsImages() != null) {
            hash *= getGoodsImages().hashCode();
        }
        if (getAppsPrice() != null) {
            hash *= getAppsPrice().hashCode();
        }
        if (getLogisticsWeigth() != null) {
            hash *= getLogisticsWeigth().hashCode();
        }
        if (getGoodsLocation() != null) {
            hash *= getGoodsLocation().hashCode();
        }
        if (getGoodsBarcode() != null) {
            hash *= getGoodsBarcode().hashCode();
        }
        if (getCreateTime() != null) {
            hash *= getCreateTime().hashCode();
        }
        if (getIsPutaway() != null) {
            hash *= getIsPutaway().hashCode();
        }
        if (getGoodsDesc() != null) {
            hash *= getGoodsDesc().hashCode();
        }
        if (getAppsDes() != null) {
            hash *= getAppsDes().hashCode();
        }
        return hash;
    }
}