package com.yuguo.net.model;

import java.io.Serializable;

public class MallGoodsInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.STORE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private Integer storeNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsRepair;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.SALES_RETURN
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String salesReturn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.RECOMMEND_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String recommendGoods;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.OTHER_INFO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String otherInfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.MERCHANT_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String merchantNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.LOGISTICS_VOLUME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String logisticsVolume;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.CLASS_FEATURE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String classFeature;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_VIDEO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsVideo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.CLASS_ATTRIBUTE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String classAttribute;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.UPLOAD_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String uploadStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_SCORE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private Integer goodsScore;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_TAG
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsTag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_BRAND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsBrand;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.GOODS_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.PARENT_GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String parentGoodsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ATTRIBUTE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String attributeNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ATTRIBUTE_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String attributeName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.SUB_GOODS_IDS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String subGoodsIds;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.IS_SUB_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String isSubGoods;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.PACKING_LIST
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String packingList;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.AFTER_SERVICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String afterService;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.SERVICE_PROMISE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String servicePromise;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.RECOMMEND_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String recommendType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.CARRIAGE_TEMPLATE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String carriageTemplate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String activityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String auditStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.UNPASS_REASON
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String unpassReason;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.AD_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String adId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.PROCUREMENT_AREA
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String procurementArea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.STORE_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String storeType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.COUNTRY
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String country;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.IS_NEW
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String isNew;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.STORE_MINUS_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String storeMinusType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.IS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String isRepair;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.OPENER_BILL
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String openerBill;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.IS_VIP
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String isVip;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ACTIVITY_RECOMMEND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String activityRecommend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.IS_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String isRefund;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.SEVENDATES_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String sevendatesRefund;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.ACTIVITY_TITLE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String activityTitle;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.COMMENT_COUNT
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String commentCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.COST_PRICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String costPrice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.REMARK
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_mall_goods_info.STANDARD_PARAM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private byte[] standardParam;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_mall_goods_info
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 构造函数
     */
    public MallGoodsInfo() {
        //Auto-generated Constructor stub
    }

    /**
     * 构造函数
     * @param goodsId goodsId
     * @param id id
     */
    public MallGoodsInfo(String goodsId, Long id) {
        this.goodsId = goodsId;
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_ID
     *
     * @return the value of t_mall_goods_info.GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_ID
     *
     * @param goodsId the value for t_mall_goods_info.GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ID
     *
     * @return the value of t_mall_goods_info.ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ID
     *
     * @param id the value for t_mall_goods_info.ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.STORE_NUM
     *
     * @return the value of t_mall_goods_info.STORE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public Integer getStoreNum() {
        return storeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.STORE_NUM
     *
     * @param storeNum the value for t_mall_goods_info.STORE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setStoreNum(Integer storeNum) {
        this.storeNum = storeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_REPAIR
     *
     * @return the value of t_mall_goods_info.GOODS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsRepair() {
        return goodsRepair;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_REPAIR
     *
     * @param goodsRepair the value for t_mall_goods_info.GOODS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsRepair(String goodsRepair) {
        this.goodsRepair = goodsRepair;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.SALES_RETURN
     *
     * @return the value of t_mall_goods_info.SALES_RETURN
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getSalesReturn() {
        return salesReturn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.SALES_RETURN
     *
     * @param salesReturn the value for t_mall_goods_info.SALES_RETURN
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setSalesReturn(String salesReturn) {
        this.salesReturn = salesReturn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.RECOMMEND_GOODS
     *
     * @return the value of t_mall_goods_info.RECOMMEND_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getRecommendGoods() {
        return recommendGoods;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.RECOMMEND_GOODS
     *
     * @param recommendGoods the value for t_mall_goods_info.RECOMMEND_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setRecommendGoods(String recommendGoods) {
        this.recommendGoods = recommendGoods;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.OTHER_INFO
     *
     * @return the value of t_mall_goods_info.OTHER_INFO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getOtherInfo() {
        return otherInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.OTHER_INFO
     *
     * @param otherInfo the value for t_mall_goods_info.OTHER_INFO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setOtherInfo(String otherInfo) {
        this.otherInfo = otherInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.MERCHANT_NUM
     *
     * @return the value of t_mall_goods_info.MERCHANT_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getMerchantNum() {
        return merchantNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.MERCHANT_NUM
     *
     * @param merchantNum the value for t_mall_goods_info.MERCHANT_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setMerchantNum(String merchantNum) {
        this.merchantNum = merchantNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.LOGISTICS_VOLUME
     *
     * @return the value of t_mall_goods_info.LOGISTICS_VOLUME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getLogisticsVolume() {
        return logisticsVolume;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.LOGISTICS_VOLUME
     *
     * @param logisticsVolume the value for t_mall_goods_info.LOGISTICS_VOLUME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setLogisticsVolume(String logisticsVolume) {
        this.logisticsVolume = logisticsVolume;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.CLASS_FEATURE
     *
     * @return the value of t_mall_goods_info.CLASS_FEATURE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getClassFeature() {
        return classFeature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.CLASS_FEATURE
     *
     * @param classFeature the value for t_mall_goods_info.CLASS_FEATURE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setClassFeature(String classFeature) {
        this.classFeature = classFeature;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_VIDEO
     *
     * @return the value of t_mall_goods_info.GOODS_VIDEO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsVideo() {
        return goodsVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_VIDEO
     *
     * @param goodsVideo the value for t_mall_goods_info.GOODS_VIDEO
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsVideo(String goodsVideo) {
        this.goodsVideo = goodsVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_STATUS
     *
     * @return the value of t_mall_goods_info.GOODS_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_STATUS
     *
     * @param goodsStatus the value for t_mall_goods_info.GOODS_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsStatus(String goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.CLASS_ATTRIBUTE
     *
     * @return the value of t_mall_goods_info.CLASS_ATTRIBUTE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getClassAttribute() {
        return classAttribute;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.CLASS_ATTRIBUTE
     *
     * @param classAttribute the value for t_mall_goods_info.CLASS_ATTRIBUTE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setClassAttribute(String classAttribute) {
        this.classAttribute = classAttribute;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.UPLOAD_STATUS
     *
     * @return the value of t_mall_goods_info.UPLOAD_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getUploadStatus() {
        return uploadStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.UPLOAD_STATUS
     *
     * @param uploadStatus the value for t_mall_goods_info.UPLOAD_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setUploadStatus(String uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_SCORE
     *
     * @return the value of t_mall_goods_info.GOODS_SCORE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public Integer getGoodsScore() {
        return goodsScore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_SCORE
     *
     * @param goodsScore the value for t_mall_goods_info.GOODS_SCORE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsScore(Integer goodsScore) {
        this.goodsScore = goodsScore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_TAG
     *
     * @return the value of t_mall_goods_info.GOODS_TAG
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsTag() {
        return goodsTag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_TAG
     *
     * @param goodsTag the value for t_mall_goods_info.GOODS_TAG
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsTag(String goodsTag) {
        this.goodsTag = goodsTag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_BRAND
     *
     * @return the value of t_mall_goods_info.GOODS_BRAND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsBrand() {
        return goodsBrand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_BRAND
     *
     * @param goodsBrand the value for t_mall_goods_info.GOODS_BRAND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsBrand(String goodsBrand) {
        this.goodsBrand = goodsBrand;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.GOODS_NAME
     *
     * @return the value of t_mall_goods_info.GOODS_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.GOODS_NAME
     *
     * @param goodsName the value for t_mall_goods_info.GOODS_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.PARENT_GOODS_ID
     *
     * @return the value of t_mall_goods_info.PARENT_GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getParentGoodsId() {
        return parentGoodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.PARENT_GOODS_ID
     *
     * @param parentGoodsId the value for t_mall_goods_info.PARENT_GOODS_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setParentGoodsId(String parentGoodsId) {
        this.parentGoodsId = parentGoodsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ATTRIBUTE_NUM
     *
     * @return the value of t_mall_goods_info.ATTRIBUTE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getAttributeNum() {
        return attributeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ATTRIBUTE_NUM
     *
     * @param attributeNum the value for t_mall_goods_info.ATTRIBUTE_NUM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setAttributeNum(String attributeNum) {
        this.attributeNum = attributeNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ATTRIBUTE_NAME
     *
     * @return the value of t_mall_goods_info.ATTRIBUTE_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ATTRIBUTE_NAME
     *
     * @param attributeName the value for t_mall_goods_info.ATTRIBUTE_NAME
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.SUB_GOODS_IDS
     *
     * @return the value of t_mall_goods_info.SUB_GOODS_IDS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getSubGoodsIds() {
        return subGoodsIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.SUB_GOODS_IDS
     *
     * @param subGoodsIds the value for t_mall_goods_info.SUB_GOODS_IDS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setSubGoodsIds(String subGoodsIds) {
        this.subGoodsIds = subGoodsIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.IS_SUB_GOODS
     *
     * @return the value of t_mall_goods_info.IS_SUB_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getIsSubGoods() {
        return isSubGoods;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.IS_SUB_GOODS
     *
     * @param isSubGoods the value for t_mall_goods_info.IS_SUB_GOODS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setIsSubGoods(String isSubGoods) {
        this.isSubGoods = isSubGoods;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.PACKING_LIST
     *
     * @return the value of t_mall_goods_info.PACKING_LIST
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getPackingList() {
        return packingList;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.PACKING_LIST
     *
     * @param packingList the value for t_mall_goods_info.PACKING_LIST
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setPackingList(String packingList) {
        this.packingList = packingList;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.AFTER_SERVICE
     *
     * @return the value of t_mall_goods_info.AFTER_SERVICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getAfterService() {
        return afterService;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.AFTER_SERVICE
     *
     * @param afterService the value for t_mall_goods_info.AFTER_SERVICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setAfterService(String afterService) {
        this.afterService = afterService;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.SERVICE_PROMISE
     *
     * @return the value of t_mall_goods_info.SERVICE_PROMISE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getServicePromise() {
        return servicePromise;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.SERVICE_PROMISE
     *
     * @param servicePromise the value for t_mall_goods_info.SERVICE_PROMISE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setServicePromise(String servicePromise) {
        this.servicePromise = servicePromise;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.RECOMMEND_TYPE
     *
     * @return the value of t_mall_goods_info.RECOMMEND_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getRecommendType() {
        return recommendType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.RECOMMEND_TYPE
     *
     * @param recommendType the value for t_mall_goods_info.RECOMMEND_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setRecommendType(String recommendType) {
        this.recommendType = recommendType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.CARRIAGE_TEMPLATE
     *
     * @return the value of t_mall_goods_info.CARRIAGE_TEMPLATE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getCarriageTemplate() {
        return carriageTemplate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.CARRIAGE_TEMPLATE
     *
     * @param carriageTemplate the value for t_mall_goods_info.CARRIAGE_TEMPLATE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setCarriageTemplate(String carriageTemplate) {
        this.carriageTemplate = carriageTemplate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ACTIVITY_ID
     *
     * @return the value of t_mall_goods_info.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ACTIVITY_ID
     *
     * @param activityId the value for t_mall_goods_info.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.AUDIT_STATUS
     *
     * @return the value of t_mall_goods_info.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.AUDIT_STATUS
     *
     * @param auditStatus the value for t_mall_goods_info.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.UNPASS_REASON
     *
     * @return the value of t_mall_goods_info.UNPASS_REASON
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getUnpassReason() {
        return unpassReason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.UNPASS_REASON
     *
     * @param unpassReason the value for t_mall_goods_info.UNPASS_REASON
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setUnpassReason(String unpassReason) {
        this.unpassReason = unpassReason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.AD_ID
     *
     * @return the value of t_mall_goods_info.AD_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.AD_ID
     *
     * @param adId the value for t_mall_goods_info.AD_ID
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setAdId(String adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.PROCUREMENT_AREA
     *
     * @return the value of t_mall_goods_info.PROCUREMENT_AREA
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getProcurementArea() {
        return procurementArea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.PROCUREMENT_AREA
     *
     * @param procurementArea the value for t_mall_goods_info.PROCUREMENT_AREA
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setProcurementArea(String procurementArea) {
        this.procurementArea = procurementArea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.STORE_TYPE
     *
     * @return the value of t_mall_goods_info.STORE_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.STORE_TYPE
     *
     * @param storeType the value for t_mall_goods_info.STORE_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setStoreType(String storeType) {
        this.storeType = storeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.COUNTRY
     *
     * @return the value of t_mall_goods_info.COUNTRY
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.COUNTRY
     *
     * @param country the value for t_mall_goods_info.COUNTRY
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.IS_NEW
     *
     * @return the value of t_mall_goods_info.IS_NEW
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.IS_NEW
     *
     * @param isNew the value for t_mall_goods_info.IS_NEW
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setIsNew(String isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.STORE_MINUS_TYPE
     *
     * @return the value of t_mall_goods_info.STORE_MINUS_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getStoreMinusType() {
        return storeMinusType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.STORE_MINUS_TYPE
     *
     * @param storeMinusType the value for t_mall_goods_info.STORE_MINUS_TYPE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setStoreMinusType(String storeMinusType) {
        this.storeMinusType = storeMinusType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.IS_REPAIR
     *
     * @return the value of t_mall_goods_info.IS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getIsRepair() {
        return isRepair;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.IS_REPAIR
     *
     * @param isRepair the value for t_mall_goods_info.IS_REPAIR
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setIsRepair(String isRepair) {
        this.isRepair = isRepair;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.OPENER_BILL
     *
     * @return the value of t_mall_goods_info.OPENER_BILL
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getOpenerBill() {
        return openerBill;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.OPENER_BILL
     *
     * @param openerBill the value for t_mall_goods_info.OPENER_BILL
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setOpenerBill(String openerBill) {
        this.openerBill = openerBill;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.IS_VIP
     *
     * @return the value of t_mall_goods_info.IS_VIP
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.IS_VIP
     *
     * @param isVip the value for t_mall_goods_info.IS_VIP
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setIsVip(String isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ACTIVITY_RECOMMEND
     *
     * @return the value of t_mall_goods_info.ACTIVITY_RECOMMEND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getActivityRecommend() {
        return activityRecommend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ACTIVITY_RECOMMEND
     *
     * @param activityRecommend the value for t_mall_goods_info.ACTIVITY_RECOMMEND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setActivityRecommend(String activityRecommend) {
        this.activityRecommend = activityRecommend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.IS_REFUND
     *
     * @return the value of t_mall_goods_info.IS_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.IS_REFUND
     *
     * @param isRefund the value for t_mall_goods_info.IS_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setIsRefund(String isRefund) {
        this.isRefund = isRefund;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.SEVENDATES_REFUND
     *
     * @return the value of t_mall_goods_info.SEVENDATES_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getSevendatesRefund() {
        return sevendatesRefund;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.SEVENDATES_REFUND
     *
     * @param sevendatesRefund the value for t_mall_goods_info.SEVENDATES_REFUND
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setSevendatesRefund(String sevendatesRefund) {
        this.sevendatesRefund = sevendatesRefund;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.ACTIVITY_TITLE
     *
     * @return the value of t_mall_goods_info.ACTIVITY_TITLE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.ACTIVITY_TITLE
     *
     * @param activityTitle the value for t_mall_goods_info.ACTIVITY_TITLE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.COMMENT_COUNT
     *
     * @return the value of t_mall_goods_info.COMMENT_COUNT
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.COMMENT_COUNT
     *
     * @param commentCount the value for t_mall_goods_info.COMMENT_COUNT
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setCommentCount(String commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.COST_PRICE
     *
     * @return the value of t_mall_goods_info.COST_PRICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.COST_PRICE
     *
     * @param costPrice the value for t_mall_goods_info.COST_PRICE
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setCostPrice(String costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.REMARK
     *
     * @return the value of t_mall_goods_info.REMARK
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.REMARK
     *
     * @param remark the value for t_mall_goods_info.REMARK
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_mall_goods_info.STANDARD_PARAM
     *
     * @return the value of t_mall_goods_info.STANDARD_PARAM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public byte[] getStandardParam() {
        return standardParam;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_mall_goods_info.STANDARD_PARAM
     *
     * @param standardParam the value for t_mall_goods_info.STANDARD_PARAM
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    public void setStandardParam(byte[] standardParam) {
        this.standardParam = standardParam;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_info
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof MallGoodsInfo)) {
            return false;
        }
        MallGoodsInfo other = (MallGoodsInfo) that;
        return this.getGoodsId() == null ? other == null : this.getGoodsId().equals(other.getGoodsId())
            && this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getStoreNum() == null ? other == null : this.getStoreNum().equals(other.getStoreNum())
            && this.getGoodsRepair() == null ? other == null : this.getGoodsRepair().equals(other.getGoodsRepair())
            && this.getSalesReturn() == null ? other == null : this.getSalesReturn().equals(other.getSalesReturn())
            && this.getRecommendGoods() == null ? other == null : this.getRecommendGoods().equals(other.getRecommendGoods())
            && this.getOtherInfo() == null ? other == null : this.getOtherInfo().equals(other.getOtherInfo())
            && this.getMerchantNum() == null ? other == null : this.getMerchantNum().equals(other.getMerchantNum())
            && this.getLogisticsVolume() == null ? other == null : this.getLogisticsVolume().equals(other.getLogisticsVolume())
            && this.getClassFeature() == null ? other == null : this.getClassFeature().equals(other.getClassFeature())
            && this.getGoodsVideo() == null ? other == null : this.getGoodsVideo().equals(other.getGoodsVideo())
            && this.getGoodsStatus() == null ? other == null : this.getGoodsStatus().equals(other.getGoodsStatus())
            && this.getClassAttribute() == null ? other == null : this.getClassAttribute().equals(other.getClassAttribute())
            && this.getUploadStatus() == null ? other == null : this.getUploadStatus().equals(other.getUploadStatus())
            && this.getGoodsScore() == null ? other == null : this.getGoodsScore().equals(other.getGoodsScore())
            && this.getGoodsTag() == null ? other == null : this.getGoodsTag().equals(other.getGoodsTag())
            && this.getGoodsBrand() == null ? other == null : this.getGoodsBrand().equals(other.getGoodsBrand())
            && this.getGoodsName() == null ? other == null : this.getGoodsName().equals(other.getGoodsName())
            && this.getParentGoodsId() == null ? other == null : this.getParentGoodsId().equals(other.getParentGoodsId())
            && this.getAttributeNum() == null ? other == null : this.getAttributeNum().equals(other.getAttributeNum())
            && this.getAttributeName() == null ? other == null : this.getAttributeName().equals(other.getAttributeName())
            && this.getSubGoodsIds() == null ? other == null : this.getSubGoodsIds().equals(other.getSubGoodsIds())
            && this.getIsSubGoods() == null ? other == null : this.getIsSubGoods().equals(other.getIsSubGoods())
            && this.getPackingList() == null ? other == null : this.getPackingList().equals(other.getPackingList())
            && this.getAfterService() == null ? other == null : this.getAfterService().equals(other.getAfterService())
            && this.getServicePromise() == null ? other == null : this.getServicePromise().equals(other.getServicePromise())
            && this.getRecommendType() == null ? other == null : this.getRecommendType().equals(other.getRecommendType())
            && this.getCarriageTemplate() == null ? other == null : this.getCarriageTemplate().equals(other.getCarriageTemplate())
            && this.getActivityId() == null ? other == null : this.getActivityId().equals(other.getActivityId())
            && this.getAuditStatus() == null ? other == null : this.getAuditStatus().equals(other.getAuditStatus())
            && this.getUnpassReason() == null ? other == null : this.getUnpassReason().equals(other.getUnpassReason())
            && this.getAdId() == null ? other == null : this.getAdId().equals(other.getAdId())
            && this.getProcurementArea() == null ? other == null : this.getProcurementArea().equals(other.getProcurementArea())
            && this.getStoreType() == null ? other == null : this.getStoreType().equals(other.getStoreType())
            && this.getCountry() == null ? other == null : this.getCountry().equals(other.getCountry())
            && this.getIsNew() == null ? other == null : this.getIsNew().equals(other.getIsNew())
            && this.getStoreMinusType() == null ? other == null : this.getStoreMinusType().equals(other.getStoreMinusType())
            && this.getIsRepair() == null ? other == null : this.getIsRepair().equals(other.getIsRepair())
            && this.getOpenerBill() == null ? other == null : this.getOpenerBill().equals(other.getOpenerBill())
            && this.getIsVip() == null ? other == null : this.getIsVip().equals(other.getIsVip())
            && this.getActivityRecommend() == null ? other == null : this.getActivityRecommend().equals(other.getActivityRecommend())
            && this.getIsRefund() == null ? other == null : this.getIsRefund().equals(other.getIsRefund())
            && this.getSevendatesRefund() == null ? other == null : this.getSevendatesRefund().equals(other.getSevendatesRefund())
            && this.getActivityTitle() == null ? other == null : this.getActivityTitle().equals(other.getActivityTitle())
            && this.getCommentCount() == null ? other == null : this.getCommentCount().equals(other.getCommentCount())
            && this.getCostPrice() == null ? other == null : this.getCostPrice().equals(other.getCostPrice())
            && this.getRemark() == null ? other == null : this.getRemark().equals(other.getRemark())
            && this.getStandardParam() == null ? other == null : this.getStandardParam().equals(other.getStandardParam());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_info
     *
     * @ibatorgenerated Thu Dec 22 10:37:24 CST 2016
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGoodsId() != null) {
            hash *= getGoodsId().hashCode();
        }
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getStoreNum() != null) {
            hash *= getStoreNum().hashCode();
        }
        if (getGoodsRepair() != null) {
            hash *= getGoodsRepair().hashCode();
        }
        if (getSalesReturn() != null) {
            hash *= getSalesReturn().hashCode();
        }
        if (getRecommendGoods() != null) {
            hash *= getRecommendGoods().hashCode();
        }
        if (getOtherInfo() != null) {
            hash *= getOtherInfo().hashCode();
        }
        if (getMerchantNum() != null) {
            hash *= getMerchantNum().hashCode();
        }
        if (getLogisticsVolume() != null) {
            hash *= getLogisticsVolume().hashCode();
        }
        if (getClassFeature() != null) {
            hash *= getClassFeature().hashCode();
        }
        if (getGoodsVideo() != null) {
            hash *= getGoodsVideo().hashCode();
        }
        if (getGoodsStatus() != null) {
            hash *= getGoodsStatus().hashCode();
        }
        if (getClassAttribute() != null) {
            hash *= getClassAttribute().hashCode();
        }
        if (getUploadStatus() != null) {
            hash *= getUploadStatus().hashCode();
        }
        if (getGoodsScore() != null) {
            hash *= getGoodsScore().hashCode();
        }
        if (getGoodsTag() != null) {
            hash *= getGoodsTag().hashCode();
        }
        if (getGoodsBrand() != null) {
            hash *= getGoodsBrand().hashCode();
        }
        if (getGoodsName() != null) {
            hash *= getGoodsName().hashCode();
        }
        if (getParentGoodsId() != null) {
            hash *= getParentGoodsId().hashCode();
        }
        if (getAttributeNum() != null) {
            hash *= getAttributeNum().hashCode();
        }
        if (getAttributeName() != null) {
            hash *= getAttributeName().hashCode();
        }
        if (getSubGoodsIds() != null) {
            hash *= getSubGoodsIds().hashCode();
        }
        if (getIsSubGoods() != null) {
            hash *= getIsSubGoods().hashCode();
        }
        if (getPackingList() != null) {
            hash *= getPackingList().hashCode();
        }
        if (getAfterService() != null) {
            hash *= getAfterService().hashCode();
        }
        if (getServicePromise() != null) {
            hash *= getServicePromise().hashCode();
        }
        if (getRecommendType() != null) {
            hash *= getRecommendType().hashCode();
        }
        if (getCarriageTemplate() != null) {
            hash *= getCarriageTemplate().hashCode();
        }
        if (getActivityId() != null) {
            hash *= getActivityId().hashCode();
        }
        if (getAuditStatus() != null) {
            hash *= getAuditStatus().hashCode();
        }
        if (getUnpassReason() != null) {
            hash *= getUnpassReason().hashCode();
        }
        if (getAdId() != null) {
            hash *= getAdId().hashCode();
        }
        if (getProcurementArea() != null) {
            hash *= getProcurementArea().hashCode();
        }
        if (getStoreType() != null) {
            hash *= getStoreType().hashCode();
        }
        if (getCountry() != null) {
            hash *= getCountry().hashCode();
        }
        if (getIsNew() != null) {
            hash *= getIsNew().hashCode();
        }
        if (getStoreMinusType() != null) {
            hash *= getStoreMinusType().hashCode();
        }
        if (getIsRepair() != null) {
            hash *= getIsRepair().hashCode();
        }
        if (getOpenerBill() != null) {
            hash *= getOpenerBill().hashCode();
        }
        if (getIsVip() != null) {
            hash *= getIsVip().hashCode();
        }
        if (getActivityRecommend() != null) {
            hash *= getActivityRecommend().hashCode();
        }
        if (getIsRefund() != null) {
            hash *= getIsRefund().hashCode();
        }
        if (getSevendatesRefund() != null) {
            hash *= getSevendatesRefund().hashCode();
        }
        if (getActivityTitle() != null) {
            hash *= getActivityTitle().hashCode();
        }
        if (getCommentCount() != null) {
            hash *= getCommentCount().hashCode();
        }
        if (getCostPrice() != null) {
            hash *= getCostPrice().hashCode();
        }
        if (getRemark() != null) {
            hash *= getRemark().hashCode();
        }
        if (getStandardParam() != null) {
            hash *= getStandardParam().hashCode();
        }
        return hash;
    }
}