package com.yuguo.net.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yuguo.net.common.config.ibatis.AbstractExample;

public class SysDictionaryExample extends AbstractExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public SysDictionaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    protected SysDictionaryExample(SysDictionaryExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected List<Map<String, Object>> criteriaWithAssembledValue;

        /**
         * <p>由代码生成器创建的构造函数。</p>
         */
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
            criteriaWithAssembledValue = new ArrayList<Map<String, Object>>();
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0
                || criteriaWithAssembledValue.size() > 0;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithAssembledValue() {
            return criteriaWithAssembledValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Map<String, Object> getAssembledConditionMap(String condition, String value) {
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            return map;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        protected void addCriterion(List<? extends Object> values, String conditionEnd) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("values", values);
            map.put("conditionEnd", conditionEnd);
            criteriaWithAssembledValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdIsNull() {
            addCriterion("sysDictionary.id is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdIsNotNull() {
            addCriterion("sysDictionary.id is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdEqualTo(Long value) {
            addCriterion("sysDictionary.id =", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("sysDictionary.id <>", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdGreaterThan(Long value) {
            addCriterion("sysDictionary.id >", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sysDictionary.id >=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdLessThan(Long value) {
            addCriterion("sysDictionary.id <", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("sysDictionary.id <=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdIn(List<Long> values) {
            addCriterion("sysDictionary.id in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("sysDictionary.id not in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("sysDictionary.id between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("sysDictionary.id not between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeIsNull() {
            addCriterion("sysDictionary.dic_type is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeIsNotNull() {
            addCriterion("sysDictionary.dic_type is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeEqualTo(String value) {
            addCriterion("sysDictionary.dic_type =", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeNotEqualTo(String value) {
            addCriterion("sysDictionary.dic_type <>", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeGreaterThan(String value) {
            addCriterion("sysDictionary.dic_type >", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_type >=", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeLessThan(String value) {
            addCriterion("sysDictionary.dic_type <", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_type <=", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeLike(String value) {
            addCriterion("sysDictionary.dic_type like", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeNotLike(String value) {
            addCriterion("sysDictionary.dic_type not like", value, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeIn(List<String> values) {
            addCriterion("sysDictionary.dic_type in", values, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeNotIn(List<String> values) {
            addCriterion("sysDictionary.dic_type not in", values, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_type between", value1, value2, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicTypeNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_type not between", value1, value2, "dicType");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameIsNull() {
            addCriterion("sysDictionary.dic_name is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameIsNotNull() {
            addCriterion("sysDictionary.dic_name is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameEqualTo(String value) {
            addCriterion("sysDictionary.dic_name =", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameNotEqualTo(String value) {
            addCriterion("sysDictionary.dic_name <>", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameGreaterThan(String value) {
            addCriterion("sysDictionary.dic_name >", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_name >=", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameLessThan(String value) {
            addCriterion("sysDictionary.dic_name <", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_name <=", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameLike(String value) {
            addCriterion("sysDictionary.dic_name like", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameNotLike(String value) {
            addCriterion("sysDictionary.dic_name not like", value, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameIn(List<String> values) {
            addCriterion("sysDictionary.dic_name in", values, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameNotIn(List<String> values) {
            addCriterion("sysDictionary.dic_name not in", values, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_name between", value1, value2, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicNameNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_name not between", value1, value2, "dicName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexIsNull() {
            addCriterion("sysDictionary.dic_index is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexIsNotNull() {
            addCriterion("sysDictionary.dic_index is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexEqualTo(String value) {
            addCriterion("sysDictionary.dic_index =", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexNotEqualTo(String value) {
            addCriterion("sysDictionary.dic_index <>", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexGreaterThan(String value) {
            addCriterion("sysDictionary.dic_index >", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_index >=", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexLessThan(String value) {
            addCriterion("sysDictionary.dic_index <", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_index <=", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexLike(String value) {
            addCriterion("sysDictionary.dic_index like", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexNotLike(String value) {
            addCriterion("sysDictionary.dic_index not like", value, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexIn(List<String> values) {
            addCriterion("sysDictionary.dic_index in", values, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexNotIn(List<String> values) {
            addCriterion("sysDictionary.dic_index not in", values, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_index between", value1, value2, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicIndexNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_index not between", value1, value2, "dicIndex");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyIsNull() {
            addCriterion("sysDictionary.dic_key is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyIsNotNull() {
            addCriterion("sysDictionary.dic_key is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyEqualTo(String value) {
            addCriterion("sysDictionary.dic_key =", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyNotEqualTo(String value) {
            addCriterion("sysDictionary.dic_key <>", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyGreaterThan(String value) {
            addCriterion("sysDictionary.dic_key >", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_key >=", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyLessThan(String value) {
            addCriterion("sysDictionary.dic_key <", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.dic_key <=", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyLike(String value) {
            addCriterion("sysDictionary.dic_key like", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyNotLike(String value) {
            addCriterion("sysDictionary.dic_key not like", value, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyIn(List<String> values) {
            addCriterion("sysDictionary.dic_key in", values, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyNotIn(List<String> values) {
            addCriterion("sysDictionary.dic_key not in", values, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_key between", value1, value2, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andDicKeyNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.dic_key not between", value1, value2, "dicKey");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadIsNull() {
            addCriterion("sysDictionary.is_upload is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadIsNotNull() {
            addCriterion("sysDictionary.is_upload is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadEqualTo(String value) {
            addCriterion("sysDictionary.is_upload =", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadNotEqualTo(String value) {
            addCriterion("sysDictionary.is_upload <>", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadGreaterThan(String value) {
            addCriterion("sysDictionary.is_upload >", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.is_upload >=", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadLessThan(String value) {
            addCriterion("sysDictionary.is_upload <", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.is_upload <=", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadLike(String value) {
            addCriterion("sysDictionary.is_upload like", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadNotLike(String value) {
            addCriterion("sysDictionary.is_upload not like", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadIn(List<String> values) {
            addCriterion("sysDictionary.is_upload in", values, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadNotIn(List<String> values) {
            addCriterion("sysDictionary.is_upload not in", values, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadBetween(String value1, String value2) {
            addCriterion("sysDictionary.is_upload between", value1, value2, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andIsUploadNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.is_upload not between", value1, value2, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeIsNull() {
            addCriterion("sysDictionary.create_time is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeIsNotNull() {
            addCriterion("sysDictionary.create_time is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("sysDictionary.create_time =", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("sysDictionary.create_time <>", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("sysDictionary.create_time >", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sysDictionary.create_time >=", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("sysDictionary.create_time <", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("sysDictionary.create_time <=", value, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("sysDictionary.create_time in", values, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("sysDictionary.create_time not in", values, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("sysDictionary.create_time between", value1, value2, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("sysDictionary.create_time not between", value1, value2, "createTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkIsNull() {
            addCriterion("sysDictionary.remark is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkIsNotNull() {
            addCriterion("sysDictionary.remark is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkEqualTo(String value) {
            addCriterion("sysDictionary.remark =", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("sysDictionary.remark <>", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("sysDictionary.remark >", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sysDictionary.remark >=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkLessThan(String value) {
            addCriterion("sysDictionary.remark <", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("sysDictionary.remark <=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkLike(String value) {
            addCriterion("sysDictionary.remark like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkNotLike(String value) {
            addCriterion("sysDictionary.remark not like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkIn(List<String> values) {
            addCriterion("sysDictionary.remark in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("sysDictionary.remark not in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("sysDictionary.remark between", value1, value2, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("sysDictionary.remark not between", value1, value2, "remark");
            return this;
        }
    }
}