package com.yuguo.net.model;

import java.io.Serializable;
import java.util.Date;

public class SysPictureInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.ID
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.FILE_NAME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String fileName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.PIC_PATH
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String picPath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.LOAD_TIME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private Date loadTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.OPERATE
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String operate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.IS_UPLOAD
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String isUpload;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_sys_picture_info.REMARK
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private String remark;
    

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * 构造函数
     */
    public SysPictureInfo() {
        //Auto-generated Constructor stub
    }

    /**
     * 构造函数
     * @param id id
     */
    public SysPictureInfo(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.ID
     *
     * @return the value of t_sys_picture_info.ID
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.ID
     *
     * @param id the value for t_sys_picture_info.ID
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.FILE_NAME
     *
     * @return the value of t_sys_picture_info.FILE_NAME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.FILE_NAME
     *
     * @param fileName the value for t_sys_picture_info.FILE_NAME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.PIC_PATH
     *
     * @return the value of t_sys_picture_info.PIC_PATH
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.PIC_PATH
     *
     * @param picPath the value for t_sys_picture_info.PIC_PATH
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.LOAD_TIME
     *
     * @return the value of t_sys_picture_info.LOAD_TIME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public Date getLoadTime() {
        return loadTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.LOAD_TIME
     *
     * @param loadTime the value for t_sys_picture_info.LOAD_TIME
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setLoadTime(Date loadTime) {
        this.loadTime = loadTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.OPERATE
     *
     * @return the value of t_sys_picture_info.OPERATE
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.OPERATE
     *
     * @param operate the value for t_sys_picture_info.OPERATE
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setOperate(String operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.IS_UPLOAD
     *
     * @return the value of t_sys_picture_info.IS_UPLOAD
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getIsUpload() {
        return isUpload;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.IS_UPLOAD
     *
     * @param isUpload the value for t_sys_picture_info.IS_UPLOAD
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setIsUpload(String isUpload) {
        this.isUpload = isUpload;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_sys_picture_info.REMARK
     *
     * @return the value of t_sys_picture_info.REMARK
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_sys_picture_info.REMARK
     *
     * @param remark the value for t_sys_picture_info.REMARK
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof SysPictureInfo)) {
            return false;
        }
        SysPictureInfo other = (SysPictureInfo) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getFileName() == null ? other == null : this.getFileName().equals(other.getFileName())
            && this.getPicPath() == null ? other == null : this.getPicPath().equals(other.getPicPath())
            && this.getLoadTime() == null ? other == null : this.getLoadTime().equals(other.getLoadTime())
            && this.getOperate() == null ? other == null : this.getOperate().equals(other.getOperate())
            && this.getIsUpload() == null ? other == null : this.getIsUpload().equals(other.getIsUpload())
            && this.getRemark() == null ? other == null : this.getRemark().equals(other.getRemark());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getFileName() != null) {
            hash *= getFileName().hashCode();
        }
        if (getPicPath() != null) {
            hash *= getPicPath().hashCode();
        }
        if (getLoadTime() != null) {
            hash *= getLoadTime().hashCode();
        }
        if (getOperate() != null) {
            hash *= getOperate().hashCode();
        }
        if (getIsUpload() != null) {
            hash *= getIsUpload().hashCode();
        }
        if (getRemark() != null) {
            hash *= getRemark().hashCode();
        }
        return hash;
    }
}