package com.yuguo.net.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yuguo.net.common.config.ibatis.AbstractExample;

public class SysPictureInfoExample extends AbstractExample{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public SysPictureInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    protected SysPictureInfoExample(SysPictureInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected List<Map<String, Object>> criteriaWithAssembledValue;

        /**
         * <p>由代码生成器创建的构造函数。</p>
         */
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
            criteriaWithAssembledValue = new ArrayList<Map<String, Object>>();
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0
                || criteriaWithAssembledValue.size() > 0;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public List<Map<String, Object>> getCriteriaWithAssembledValue() {
            return criteriaWithAssembledValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Map<String, Object> getAssembledConditionMap(String condition, String value) {
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            return map;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        protected void addCriterion(List<? extends Object> values, String conditionEnd) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("values", values);
            map.put("conditionEnd", conditionEnd);
            criteriaWithAssembledValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdIsNull() {
            addCriterion("sysPictureInfo.ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdIsNotNull() {
            addCriterion("sysPictureInfo.ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdEqualTo(String value) {
            addCriterion("sysPictureInfo.ID =", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdNotEqualTo(String value) {
            addCriterion("sysPictureInfo.ID <>", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdGreaterThan(String value) {
            addCriterion("sysPictureInfo.ID >", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.ID >=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdLessThan(String value) {
            addCriterion("sysPictureInfo.ID <", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.ID <=", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdLike(String value) {
            addCriterion("sysPictureInfo.ID like", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdNotLike(String value) {
            addCriterion("sysPictureInfo.ID not like", value, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdIn(List<String> values) {
            addCriterion("sysPictureInfo.ID in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdNotIn(List<String> values) {
            addCriterion("sysPictureInfo.ID not in", values, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.ID between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.ID not between", value1, value2, "id");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameIsNull() {
            addCriterion("sysPictureInfo.FILE_NAME is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameIsNotNull() {
            addCriterion("sysPictureInfo.FILE_NAME is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameEqualTo(String value) {
            addCriterion("sysPictureInfo.FILE_NAME =", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("sysPictureInfo.FILE_NAME <>", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("sysPictureInfo.FILE_NAME >", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.FILE_NAME >=", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameLessThan(String value) {
            addCriterion("sysPictureInfo.FILE_NAME <", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.FILE_NAME <=", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameLike(String value) {
            addCriterion("sysPictureInfo.FILE_NAME like", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameNotLike(String value) {
            addCriterion("sysPictureInfo.FILE_NAME not like", value, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameIn(List<String> values) {
            addCriterion("sysPictureInfo.FILE_NAME in", values, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("sysPictureInfo.FILE_NAME not in", values, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.FILE_NAME between", value1, value2, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.FILE_NAME not between", value1, value2, "fileName");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathIsNull() {
            addCriterion("sysPictureInfo.PIC_PATH is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathIsNotNull() {
            addCriterion("sysPictureInfo.PIC_PATH is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathEqualTo(String value) {
            addCriterion("sysPictureInfo.PIC_PATH =", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathNotEqualTo(String value) {
            addCriterion("sysPictureInfo.PIC_PATH <>", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathGreaterThan(String value) {
            addCriterion("sysPictureInfo.PIC_PATH >", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.PIC_PATH >=", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathLessThan(String value) {
            addCriterion("sysPictureInfo.PIC_PATH <", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.PIC_PATH <=", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathLike(String value) {
            addCriterion("sysPictureInfo.PIC_PATH like", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathNotLike(String value) {
            addCriterion("sysPictureInfo.PIC_PATH not like", value, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathIn(List<String> values) {
            addCriterion("sysPictureInfo.PIC_PATH in", values, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathNotIn(List<String> values) {
            addCriterion("sysPictureInfo.PIC_PATH not in", values, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.PIC_PATH between", value1, value2, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andPicPathNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.PIC_PATH not between", value1, value2, "picPath");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeIsNull() {
            addCriterion("sysPictureInfo.LOAD_TIME is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeIsNotNull() {
            addCriterion("sysPictureInfo.LOAD_TIME is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeEqualTo(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME =", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeNotEqualTo(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME <>", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeGreaterThan(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME >", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME >=", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeLessThan(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME <", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeLessThanOrEqualTo(Date value) {
            addCriterion("sysPictureInfo.LOAD_TIME <=", value, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeIn(List<Date> values) {
            addCriterion("sysPictureInfo.LOAD_TIME in", values, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeNotIn(List<Date> values) {
            addCriterion("sysPictureInfo.LOAD_TIME not in", values, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeBetween(Date value1, Date value2) {
            addCriterion("sysPictureInfo.LOAD_TIME between", value1, value2, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andLoadTimeNotBetween(Date value1, Date value2) {
            addCriterion("sysPictureInfo.LOAD_TIME not between", value1, value2, "loadTime");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateIsNull() {
            addCriterion("sysPictureInfo.OPERATE is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateIsNotNull() {
            addCriterion("sysPictureInfo.OPERATE is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateEqualTo(String value) {
            addCriterion("sysPictureInfo.OPERATE =", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateNotEqualTo(String value) {
            addCriterion("sysPictureInfo.OPERATE <>", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateGreaterThan(String value) {
            addCriterion("sysPictureInfo.OPERATE >", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.OPERATE >=", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateLessThan(String value) {
            addCriterion("sysPictureInfo.OPERATE <", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.OPERATE <=", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateLike(String value) {
            addCriterion("sysPictureInfo.OPERATE like", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateNotLike(String value) {
            addCriterion("sysPictureInfo.OPERATE not like", value, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateIn(List<String> values) {
            addCriterion("sysPictureInfo.OPERATE in", values, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateNotIn(List<String> values) {
            addCriterion("sysPictureInfo.OPERATE not in", values, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.OPERATE between", value1, value2, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andOperateNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.OPERATE not between", value1, value2, "operate");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadIsNull() {
            addCriterion("sysPictureInfo.IS_UPLOAD is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadIsNotNull() {
            addCriterion("sysPictureInfo.IS_UPLOAD is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadEqualTo(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD =", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadNotEqualTo(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD <>", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadGreaterThan(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD >", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD >=", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadLessThan(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD <", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD <=", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadLike(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD like", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadNotLike(String value) {
            addCriterion("sysPictureInfo.IS_UPLOAD not like", value, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadIn(List<String> values) {
            addCriterion("sysPictureInfo.IS_UPLOAD in", values, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadNotIn(List<String> values) {
            addCriterion("sysPictureInfo.IS_UPLOAD not in", values, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.IS_UPLOAD between", value1, value2, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andIsUploadNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.IS_UPLOAD not between", value1, value2, "isUpload");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkIsNull() {
            addCriterion("sysPictureInfo.REMARK is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkIsNotNull() {
            addCriterion("sysPictureInfo.REMARK is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkEqualTo(String value) {
            addCriterion("sysPictureInfo.REMARK =", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("sysPictureInfo.REMARK <>", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("sysPictureInfo.REMARK >", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.REMARK >=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkLessThan(String value) {
            addCriterion("sysPictureInfo.REMARK <", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("sysPictureInfo.REMARK <=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkLike(String value) {
            addCriterion("sysPictureInfo.REMARK like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkNotLike(String value) {
            addCriterion("sysPictureInfo.REMARK not like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkIn(List<String> values) {
            addCriterion("sysPictureInfo.REMARK in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("sysPictureInfo.REMARK not in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.REMARK between", value1, value2, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("sysPictureInfo.REMARK not between", value1, value2, "remark");
            return this;
        }
    }
}