package com.yuguo.net.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yuguo.net.common.config.ibatis.AbstractExample;

public class SysUserAuthorityExample extends AbstractExample{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public SysUserAuthorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    protected SysUserAuthorityExample(SysUserAuthorityExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_sys_user_authority
     *
     * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected List<Map<String, Object>> criteriaWithAssembledValue;

        /**
         * <p>由代码生成器创建的构造函数。</p>
         */
        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
            criteriaWithAssembledValue = new ArrayList<Map<String, Object>>();
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0
                || criteriaWithAssembledValue.size() > 0;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public List<Map<String, Object>> getCriteriaWithAssembledValue() {
            return criteriaWithAssembledValue;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Map<String, Object> getAssembledConditionMap(String condition, String value) {
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            return map;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        protected void addCriterion(List<? extends Object> values, String conditionEnd) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("values", values);
            map.put("conditionEnd", conditionEnd);
            criteriaWithAssembledValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdIsNull() {
            addCriterion("sysUserAuthority.AUTH_ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdIsNotNull() {
            addCriterion("sysUserAuthority.AUTH_ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTH_ID =", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdNotEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTH_ID <>", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdGreaterThan(String value) {
            addCriterion("sysUserAuthority.AUTH_ID >", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdGreaterThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTH_ID >=", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdLessThan(String value) {
            addCriterion("sysUserAuthority.AUTH_ID <", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdLessThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTH_ID <=", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdLike(String value) {
            addCriterion("sysUserAuthority.AUTH_ID like", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdNotLike(String value) {
            addCriterion("sysUserAuthority.AUTH_ID not like", value, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdIn(List<String> values) {
            addCriterion("sysUserAuthority.AUTH_ID in", values, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdNotIn(List<String> values) {
            addCriterion("sysUserAuthority.AUTH_ID not in", values, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.AUTH_ID between", value1, value2, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthIdNotBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.AUTH_ID not between", value1, value2, "authId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdIsNull() {
            addCriterion("sysUserAuthority.USER_ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdIsNotNull() {
            addCriterion("sysUserAuthority.USER_ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdEqualTo(String value) {
            addCriterion("sysUserAuthority.USER_ID =", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("sysUserAuthority.USER_ID <>", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("sysUserAuthority.USER_ID >", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.USER_ID >=", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdLessThan(String value) {
            addCriterion("sysUserAuthority.USER_ID <", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.USER_ID <=", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdLike(String value) {
            addCriterion("sysUserAuthority.USER_ID like", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdNotLike(String value) {
            addCriterion("sysUserAuthority.USER_ID not like", value, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdIn(List<String> values) {
            addCriterion("sysUserAuthority.USER_ID in", values, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("sysUserAuthority.USER_ID not in", values, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.USER_ID between", value1, value2, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.USER_ID not between", value1, value2, "userId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdIsNull() {
            addCriterion("sysUserAuthority.ROLE_ID is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdIsNotNull() {
            addCriterion("sysUserAuthority.ROLE_ID is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("sysUserAuthority.ROLE_ID =", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("sysUserAuthority.ROLE_ID <>", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("sysUserAuthority.ROLE_ID >", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.ROLE_ID >=", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdLessThan(String value) {
            addCriterion("sysUserAuthority.ROLE_ID <", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.ROLE_ID <=", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdLike(String value) {
            addCriterion("sysUserAuthority.ROLE_ID like", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdNotLike(String value) {
            addCriterion("sysUserAuthority.ROLE_ID not like", value, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdIn(List<String> values) {
            addCriterion("sysUserAuthority.ROLE_ID in", values, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdNotIn(List<String> values) {
            addCriterion("sysUserAuthority.ROLE_ID not in", values, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.ROLE_ID between", value1, value2, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.ROLE_ID not between", value1, value2, "roleId");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListIsNull() {
            addCriterion("sysUserAuthority.AUTHORITY_LIST is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListIsNotNull() {
            addCriterion("sysUserAuthority.AUTHORITY_LIST is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST =", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListNotEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST <>", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListGreaterThan(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST >", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListGreaterThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST >=", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListLessThan(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST <", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListLessThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST <=", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListLike(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST like", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListNotLike(String value) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST not like", value, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListIn(List<String> values) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST in", values, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListNotIn(List<String> values) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST not in", values, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST between", value1, value2, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andAuthorityListNotBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.AUTHORITY_LIST not between", value1, value2, "authorityList");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkIsNull() {
            addCriterion("sysUserAuthority.REMARK is null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkIsNotNull() {
            addCriterion("sysUserAuthority.REMARK is not null");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkEqualTo(String value) {
            addCriterion("sysUserAuthority.REMARK =", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("sysUserAuthority.REMARK <>", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("sysUserAuthority.REMARK >", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.REMARK >=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkLessThan(String value) {
            addCriterion("sysUserAuthority.REMARK <", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("sysUserAuthority.REMARK <=", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkLike(String value) {
            addCriterion("sysUserAuthority.REMARK like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkNotLike(String value) {
            addCriterion("sysUserAuthority.REMARK not like", value, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkIn(List<String> values) {
            addCriterion("sysUserAuthority.REMARK in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("sysUserAuthority.REMARK not in", values, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.REMARK between", value1, value2, "remark");
            return this;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_user_authority
         *
         * @ibatorgenerated Fri Apr 15 15:38:44 CST 2016
         */
        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("sysUserAuthority.REMARK not between", value1, value2, "remark");
            return this;
        }
    }
}