package com.yuguo.net.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yuguo.net.common.config.ibatis.AbstractExample;

public class TSysAdvertiseExample extends AbstractExample {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public TSysAdvertiseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	protected TSysAdvertiseExample(TSysAdvertiseExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;

		protected List<Map<String, Object>> criteriaWithSingleValue;

		protected List<Map<String, Object>> criteriaWithListValue;

		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected List<Map<String, Object>> criteriaWithAssembledValue;

		/**
		 * <p>
		 * 由代码生成器创建的构造函数。
		 * </p>
		 */
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
			criteriaWithAssembledValue = new ArrayList<Map<String, Object>>();
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0 || criteriaWithAssembledValue.size() > 0;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public List<Map<String, Object>> getCriteriaWithAssembledValue() {
			return criteriaWithAssembledValue;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Map<String, Object> getAssembledConditionMap(String condition, String value) {
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			return map;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		protected void addCriterion(List<? extends Object> values, String conditionEnd) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("values", values);
			map.put("conditionEnd", conditionEnd);
			criteriaWithAssembledValue.add(map);
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdIsNull() {
			addCriterion("tSysAdvertise.AD_ID is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdIsNotNull() {
			addCriterion("tSysAdvertise.AD_ID is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_ID =", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_ID <>", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_ID >", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_ID >=", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdLessThan(String value) {
			addCriterion("tSysAdvertise.AD_ID <", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_ID <=", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdLike(String value) {
			addCriterion("tSysAdvertise.AD_ID like", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdNotLike(String value) {
			addCriterion("tSysAdvertise.AD_ID not like", value, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_ID in", values, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_ID not in", values, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_ID between", value1, value2, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIdNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_ID not between", value1, value2, "adId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleIsNull() {
			addCriterion("tSysAdvertise.AD_TITLE is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleIsNotNull() {
			addCriterion("tSysAdvertise.AD_TITLE is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TITLE =", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TITLE <>", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_TITLE >", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TITLE >=", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleLessThan(String value) {
			addCriterion("tSysAdvertise.AD_TITLE <", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TITLE <=", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleLike(String value) {
			addCriterion("tSysAdvertise.AD_TITLE like", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleNotLike(String value) {
			addCriterion("tSysAdvertise.AD_TITLE not like", value, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_TITLE in", values, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_TITLE not in", values, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_TITLE between", value1, value2, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTitleNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_TITLE not between", value1, value2, "adTitle");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeIsNull() {
			addCriterion("tSysAdvertise.AD_TYPE is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeIsNotNull() {
			addCriterion("tSysAdvertise.AD_TYPE is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TYPE =", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TYPE <>", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_TYPE >", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TYPE >=", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeLessThan(String value) {
			addCriterion("tSysAdvertise.AD_TYPE <", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_TYPE <=", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeLike(String value) {
			addCriterion("tSysAdvertise.AD_TYPE like", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeNotLike(String value) {
			addCriterion("tSysAdvertise.AD_TYPE not like", value, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_TYPE in", values, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_TYPE not in", values, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_TYPE between", value1, value2, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdTypeNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_TYPE not between", value1, value2, "adType");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlIsNull() {
			addCriterion("tSysAdvertise.IMAGE_URL is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlIsNotNull() {
			addCriterion("tSysAdvertise.IMAGE_URL is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlEqualTo(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL =", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlNotEqualTo(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL <>", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlGreaterThan(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL >", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL >=", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlLessThan(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL <", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL <=", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlLike(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL like", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlNotLike(String value) {
			addCriterion("tSysAdvertise.IMAGE_URL not like", value, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlIn(List<String> values) {
			addCriterion("tSysAdvertise.IMAGE_URL in", values, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlNotIn(List<String> values) {
			addCriterion("tSysAdvertise.IMAGE_URL not in", values, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.IMAGE_URL between", value1, value2, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andImageUrlNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.IMAGE_URL not between", value1, value2, "imageUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescIsNull() {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescIsNotNull() {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC =", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC <>", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC >", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC >=", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescLessThan(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC <", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC <=", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescLike(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC like", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescNotLike(String value) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC not like", value, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC in", values, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC not in", values, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC between", value1, value2, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdDetailDescNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_DETAIL_DESC not between", value1, value2, "adDetailDesc");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlIsNull() {
			addCriterion("tSysAdvertise.AD_URL is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlIsNotNull() {
			addCriterion("tSysAdvertise.AD_URL is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_URL =", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_URL <>", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_URL >", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_URL >=", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlLessThan(String value) {
			addCriterion("tSysAdvertise.AD_URL <", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_URL <=", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlLike(String value) {
			addCriterion("tSysAdvertise.AD_URL like", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlNotLike(String value) {
			addCriterion("tSysAdvertise.AD_URL not like", value, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_URL in", values, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_URL not in", values, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_URL between", value1, value2, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdUrlNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_URL not between", value1, value2, "adUrl");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeIsNull() {
			addCriterion("tSysAdvertise.AD_BEGINTIME is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeIsNotNull() {
			addCriterion("tSysAdvertise.AD_BEGINTIME is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME =", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeNotEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME <>", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeGreaterThan(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME >", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeGreaterThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME >=", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeLessThan(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME <", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeLessThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_BEGINTIME <=", value, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeIn(List<Date> values) {
			addCriterion("tSysAdvertise.AD_BEGINTIME in", values, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeNotIn(List<Date> values) {
			addCriterion("tSysAdvertise.AD_BEGINTIME not in", values, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.AD_BEGINTIME between", value1, value2, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdBegintimeNotBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.AD_BEGINTIME not between", value1, value2, "adBegintime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeIsNull() {
			addCriterion("tSysAdvertise.AD_ENDTIME is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeIsNotNull() {
			addCriterion("tSysAdvertise.AD_ENDTIME is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME =", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeNotEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME <>", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeGreaterThan(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME >", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME >=", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeLessThan(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME <", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.AD_ENDTIME <=", value, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeIn(List<Date> values) {
			addCriterion("tSysAdvertise.AD_ENDTIME in", values, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeNotIn(List<Date> values) {
			addCriterion("tSysAdvertise.AD_ENDTIME not in", values, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.AD_ENDTIME between", value1, value2, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.AD_ENDTIME not between", value1, value2, "adEndtime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdIsNull() {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdIsNotNull() {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID =", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdNotEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID <>", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdGreaterThan(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID >", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID >=", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdLessThan(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID <", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID <=", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdLike(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID like", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdNotLike(String value) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID not like", value, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID in", values, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdNotIn(List<String> values) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID not in", values, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID between", value1, value2, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdCustomerIdNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.AD_CUSTOMER_ID not between", value1, value2, "adCustomerId");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeIsNull() {
			addCriterion("tSysAdvertise.CREATE_TIME is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeIsNotNull() {
			addCriterion("tSysAdvertise.CREATE_TIME is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME =", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME <>", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME >", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME >=", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME <", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("tSysAdvertise.CREATE_TIME <=", value, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("tSysAdvertise.CREATE_TIME in", values, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("tSysAdvertise.CREATE_TIME not in", values, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("tSysAdvertise.CREATE_TIME not between", value1, value2, "createTime");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationIsNull() {
			addCriterion("tSysAdvertise.AD_LOCATION is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationIsNotNull() {
			addCriterion("tSysAdvertise.AD_LOCATION is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION =", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationNotEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION <>", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationGreaterThan(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION >", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationGreaterThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION >=", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationLessThan(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION <", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationLessThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_LOCATION <=", value, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_LOCATION in", values, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationNotIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_LOCATION not in", values, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_LOCATION between", value1, value2, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdLocationNotBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_LOCATION not between", value1, value2, "adLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationIsNull() {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationIsNotNull() {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION =", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationNotEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION <>", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationGreaterThan(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION >", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationGreaterThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION >=", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationLessThan(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION <", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationLessThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION <=", value, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION in", values, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationNotIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION not in", values, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION between", value1, value2, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdPageLocationNotBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_PAGE_LOCATION not between", value1, value2, "adPageLocation");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightIsNull() {
			addCriterion("tSysAdvertise.AD_HEIGHT is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightIsNotNull() {
			addCriterion("tSysAdvertise.AD_HEIGHT is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT =", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightNotEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT <>", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightGreaterThan(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT >", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT >=", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightLessThan(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT <", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightLessThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_HEIGHT <=", value, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_HEIGHT in", values, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightNotIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_HEIGHT not in", values, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_HEIGHT between", value1, value2, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_HEIGHT not between", value1, value2, "adHeight");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexIsNull() {
			addCriterion("tSysAdvertise.AD_INDEX is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexIsNotNull() {
			addCriterion("tSysAdvertise.AD_INDEX is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX =", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexNotEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX <>", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexGreaterThan(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX >", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexGreaterThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX >=", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexLessThan(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX <", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexLessThanOrEqualTo(Integer value) {
			addCriterion("tSysAdvertise.AD_INDEX <=", value, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_INDEX in", values, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexNotIn(List<Integer> values) {
			addCriterion("tSysAdvertise.AD_INDEX not in", values, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_INDEX between", value1, value2, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andAdIndexNotBetween(Integer value1, Integer value2) {
			addCriterion("tSysAdvertise.AD_INDEX not between", value1, value2, "adIndex");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkIsNull() {
			addCriterion("tSysAdvertise.REMARK is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkIsNotNull() {
			addCriterion("tSysAdvertise.REMARK is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK =", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK <>", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("tSysAdvertise.REMARK >", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK >=", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkLessThan(String value) {
			addCriterion("tSysAdvertise.REMARK <", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK <=", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkLike(String value) {
			addCriterion("tSysAdvertise.REMARK like", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkNotLike(String value) {
			addCriterion("tSysAdvertise.REMARK not like", value, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkIn(List<String> values) {
			addCriterion("tSysAdvertise.REMARK in", values, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("tSysAdvertise.REMARK not in", values, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK between", value1, value2, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK not between", value1, value2, "remark");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1IsNull() {
			addCriterion("tSysAdvertise.REMARK1 is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1IsNotNull() {
			addCriterion("tSysAdvertise.REMARK1 is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1EqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK1 =", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1NotEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK1 <>", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1GreaterThan(String value) {
			addCriterion("tSysAdvertise.REMARK1 >", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1GreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK1 >=", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1LessThan(String value) {
			addCriterion("tSysAdvertise.REMARK1 <", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1LessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK1 <=", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1Like(String value) {
			addCriterion("tSysAdvertise.REMARK1 like", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1NotLike(String value) {
			addCriterion("tSysAdvertise.REMARK1 not like", value, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1In(List<String> values) {
			addCriterion("tSysAdvertise.REMARK1 in", values, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1NotIn(List<String> values) {
			addCriterion("tSysAdvertise.REMARK1 not in", values, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1Between(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK1 between", value1, value2, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark1NotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK1 not between", value1, value2, "remark1");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2IsNull() {
			addCriterion("tSysAdvertise.REMARK2 is null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2IsNotNull() {
			addCriterion("tSysAdvertise.REMARK2 is not null");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2EqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK2 =", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2NotEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK2 <>", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2GreaterThan(String value) {
			addCriterion("tSysAdvertise.REMARK2 >", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2GreaterThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK2 >=", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2LessThan(String value) {
			addCriterion("tSysAdvertise.REMARK2 <", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2LessThanOrEqualTo(String value) {
			addCriterion("tSysAdvertise.REMARK2 <=", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2Like(String value) {
			addCriterion("tSysAdvertise.REMARK2 like", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2NotLike(String value) {
			addCriterion("tSysAdvertise.REMARK2 not like", value, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2In(List<String> values) {
			addCriterion("tSysAdvertise.REMARK2 in", values, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2NotIn(List<String> values) {
			addCriterion("tSysAdvertise.REMARK2 not in", values, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2Between(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK2 between", value1, value2, "remark2");
			return this;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		public Criteria andRemark2NotBetween(String value1, String value2) {
			addCriterion("tSysAdvertise.REMARK2 not between", value1, value2, "remark2");
			return this;
		}
	}
}