package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.model.MallGoods;
import com.yuguo.net.model.MallGoodsExample;

public interface IMallGoodsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int countByExample(MallGoodsExample example);

	int countTwoByExample(MallGoodsExample example);
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int deleteByExample(MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int deleteByPrimaryKey(String goodsId, Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    void insert(MallGoods record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    void insertSelective(MallGoods record);

	List<MallGoods> selectTwoTable(MallGoodsExample example);
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    List<MallGoods> selectByExampleWithBLOBs(MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    List<MallGoods> selectByExampleWithoutBLOBs(MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    MallGoods selectByPrimaryKey(String goodsId, Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByExampleSelective(MallGoods record, MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByExample(MallGoods record, MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByExampleWithoutBLOBs(MallGoods record, MallGoodsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByPrimaryKeySelective(MallGoods record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MallGoods record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    int updateByPrimaryKeyWithoutBLOBs(MallGoods record);
    
    List<MallGoods> selectTwoTableWithBLOBs(MallGoodsExample example);

	List<MallGoods> selectGoodsIdByGoodsClass(String goodsClass);
}