package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.model.SysPictureInfo;
import com.yuguo.net.model.SysPictureInfoExample;

public interface ISysPictureInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int countByExample(SysPictureInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int deleteByExample(SysPictureInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    void insert(SysPictureInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    void insertSelective(SysPictureInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    List<SysPictureInfo> selectByExample(SysPictureInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    SysPictureInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int updateByExampleSelective(SysPictureInfo record, SysPictureInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int updateByExample(SysPictureInfo record, SysPictureInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int updateByPrimaryKeySelective(SysPictureInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    int updateByPrimaryKey(SysPictureInfo record);
    
	int updateByFileNameList(SysPictureInfo record,SysPictureInfoExample example);
	
}