package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.model.SysDictionary;
import com.yuguo.net.model.SysDictionaryExample;

public interface ISysDictionaryDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int countByExample(SysDictionaryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int deleteByExample(SysDictionaryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    void insert(SysDictionary record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    void insertSelective(SysDictionary record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    List<SysDictionary> selectByExample(SysDictionaryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    SysDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int updateByExampleSelective(SysDictionary record, SysDictionaryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int updateByExample(SysDictionary record, SysDictionaryExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int updateByPrimaryKeySelective(SysDictionary record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    int updateByPrimaryKey(SysDictionary record);
}