package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.model.TSysAdvertise;
import com.yuguo.net.model.TSysAdvertiseExample;

public interface ITSysAdvertiseDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int countByExample(TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int deleteByExample(TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int deleteByPrimaryKey(String adId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    void insert(TSysAdvertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    void insertSelective(TSysAdvertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    List<TSysAdvertise> selectByExampleWithBLOBs(TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    List<TSysAdvertise> selectByExampleWithoutBLOBs(TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    TSysAdvertise selectByPrimaryKey(String adId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByExampleSelective(TSysAdvertise record, TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByExample(TSysAdvertise record, TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByExampleWithoutBLOBs(TSysAdvertise record, TSysAdvertiseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByPrimaryKeySelective(TSysAdvertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TSysAdvertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise
     *
     * @ibatorgenerated Tue Dec 06 10:58:17 CST 2016
     */
    int updateByPrimaryKeyWithoutBLOBs(TSysAdvertise record);
}