package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.MallGoodsClass;
import com.yuguo.net.model.MallGoodsClassExample;

public class MallGoodsClassDAO extends GenericDAO<MallGoodsClass,MallGoodsClassExample> implements IMallGoodsClassDAO{

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public MallGoodsClassDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int countByExample(MallGoodsClassExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MallGoodsClass.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int deleteByExample(MallGoodsClassExample example) {
        int rows = getSqlMapClientTemplate().delete("MallGoodsClass.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        MallGoodsClass key = new MallGoodsClass();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("MallGoodsClass.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public void insert(MallGoodsClass record) {
        getSqlMapClientTemplate().insert("MallGoodsClass.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public void insertSelective(MallGoodsClass record) {
        getSqlMapClientTemplate().insert("MallGoodsClass.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<MallGoodsClass> selectByExample(MallGoodsClassExample example) {
        List<MallGoodsClass> list = getSqlMapClientTemplate().queryForList("MallGoodsClass.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public MallGoodsClass selectByPrimaryKey(String id) {
        MallGoodsClass key = new MallGoodsClass();
        key.setId(id);
        MallGoodsClass record = (MallGoodsClass) getSqlMapClientTemplate().queryForObject("MallGoodsClass.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int updateByExampleSelective(MallGoodsClass record, MallGoodsClassExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MallGoodsClass.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int updateByExample(MallGoodsClass record, MallGoodsClassExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MallGoodsClass.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int updateByPrimaryKeySelective(MallGoodsClass record) {
        int rows = getSqlMapClientTemplate().update("MallGoodsClass.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods_class
     *
     * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
     */
    public int updateByPrimaryKey(MallGoodsClass record) {
        int rows = getSqlMapClientTemplate().update("MallGoodsClass.updateByPrimaryKey", record);
        return rows;
    }

    /**
    /**
     * <p>t_mall_goods_class查询条件参数。</p>
     */
    private static class UpdateByExampleParms extends MallGoodsClassExample {
        private MallGoodsClass record;

        /**
         * <p>UpdateByExampleParms构造函数。</p>
         * @param record 实体
         * @param example 条件
         */
        public UpdateByExampleParms(MallGoodsClass record, MallGoodsClassExample example) {
            super(example);
            this.record = record;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods_class
         *
         * @ibatorgenerated Wed Dec 30 10:12:21 CST 2015
         */
        @SuppressWarnings("unused")
        public MallGoodsClass getRecord() {
            return record;
        }
    }

	public int selectClassMaxIndexByExample(MallGoodsClassExample example) {
		String count = getSqlMapClientTemplate().queryForObject("MallGoodsClass.selectClassMaxIndexByExample", example)+"";
		int result=0;
		if(count!=null && !"".equals(count) && !"null".equals(count)){
			result=Integer.parseInt(count);
		}
        return result;
	}

	/**
	 * 获取热搜词分类集合
	 * @return
	 * */
	@SuppressWarnings("unchecked")
	public List<MallGoodsClass> getClassNameForHotWords() {
		List<MallGoodsClass> list = getSqlMapClientTemplate().queryForList("MallGoodsClass.selectClassNameForHotWords");
		return list;
	}
	
    
}