package com.yuguo.net.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.MallGoods;
import com.yuguo.net.model.MallGoodsExample;

public class MallGoodsDAO extends GenericDAO<MallGoods,MallGoodsExample> implements IMallGoodsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public MallGoodsDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int countByExample(MallGoodsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MallGoods.countByExample", example);
        return count;
    }

 	public int countTwoByExample(MallGoodsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MallGoods.countTwoByExample", example);
        return count;
    }
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int deleteByExample(MallGoodsExample example) {
        int rows = getSqlMapClientTemplate().delete("MallGoods.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int deleteByPrimaryKey(String goodsId, Long id) {
        MallGoods key = new MallGoods();
        key.setGoodsId(goodsId);
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("MallGoods.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void insert(MallGoods record) {
        getSqlMapClientTemplate().insert("MallGoods.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public void insertSelective(MallGoods record) {
        getSqlMapClientTemplate().insert("MallGoods.insertSelective", record);
    }
    
    /**
     * 查询外键关联的两表数据
     *
     * @ibatorgenerated Wed Jun 17 16:02:12 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<MallGoods> selectTwoTable(MallGoodsExample example) {
        List<MallGoods> list = getSqlMapClientTemplate().queryForList("MallGoods.selectTwoTable", example);
        return list;
    }
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<MallGoods> selectByExampleWithBLOBs(MallGoodsExample example) {
        List<MallGoods> list = getSqlMapClientTemplate().queryForList("MallGoods.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<MallGoods> selectByExampleWithoutBLOBs(MallGoodsExample example) {
        List<MallGoods> list = getSqlMapClientTemplate().queryForList("MallGoods.selectByExampleWithoutBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public MallGoods selectByPrimaryKey(String goodsId, Long id) {
        MallGoods key = new MallGoods();
        key.setGoodsId(goodsId);
        key.setId(id);
        MallGoods record = (MallGoods) getSqlMapClientTemplate().queryForObject("MallGoods.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByExampleSelective(MallGoods record, MallGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByExample(MallGoods record, MallGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByExampleWithoutBLOBs(MallGoods record, MallGoodsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByExampleWithoutBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByPrimaryKeySelective(MallGoods record) {
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByPrimaryKeyWithBLOBs(MallGoods record) {
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_mall_goods
     *
     * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
     */
    public int updateByPrimaryKeyWithoutBLOBs(MallGoods record) {
        int rows = getSqlMapClientTemplate().update("MallGoods.updateByPrimaryKeyWithoutBLOBs", record);
        return rows;
    }

    /**
    /**
     * <p>t_mall_goods查询条件参数。</p>
     */
    private static class UpdateByExampleParms extends MallGoodsExample {
        private MallGoods record;

        /**
         * <p>UpdateByExampleParms构造函数。</p>
         * @param record 实体
         * @param example 条件
         */
        public UpdateByExampleParms(MallGoods record, MallGoodsExample example) {
            super(example);
            this.record = record;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_mall_goods
         *
         * @ibatorgenerated Wed Jun 22 12:03:21 CST 2016
         */
        @SuppressWarnings("unused")
        public MallGoods getRecord() {
            return record;
        }
    }

	public List<MallGoods> selectTwoTableWithBLOBs(MallGoodsExample example) {
		 @SuppressWarnings("unchecked")
		List<MallGoods> list = getSqlMapClientTemplate().queryForList("MallGoods.selectTwoTableWithBLOBs", example);
	     return list;
	}
	
	public List<MallGoods> selectGoodsIdByGoodsClass(String goodsClass) {
		Map<String,Object> map = new HashMap<String, Object>();
		map.put("goodsClass", goodsClass);
		List<MallGoods> list = getSqlMapClientTemplate().queryForList("MallGoods.selectGoodsIdByGoodsClass",map);
		return list;
	}
}