package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.SysAdvertiseAdmin;
import com.yuguo.net.model.SysAdvertiseAdminExample;

public class SysAdvertiseAdminDAO extends GenericDAO<SysAdvertiseAdmin,SysAdvertiseAdminExample> implements ISysAdvertiseAdminDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public SysAdvertiseAdminDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int countByExample(SysAdvertiseAdminExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SysAdvertiseAdmin.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int deleteByExample(SysAdvertiseAdminExample example) {
        int rows = getSqlMapClientTemplate().delete("SysAdvertiseAdmin.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int deleteByPrimaryKey(String adId) {
        SysAdvertiseAdmin key = new SysAdvertiseAdmin();
        key.setAdId(adId);
        int rows = getSqlMapClientTemplate().delete("SysAdvertiseAdmin.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public void insert(SysAdvertiseAdmin record) {
        getSqlMapClientTemplate().insert("SysAdvertiseAdmin.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public void insertSelective(SysAdvertiseAdmin record) {
        getSqlMapClientTemplate().insert("SysAdvertiseAdmin.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<SysAdvertiseAdmin> selectByExample(SysAdvertiseAdminExample example) {
        List<SysAdvertiseAdmin> list = getSqlMapClientTemplate().queryForList("SysAdvertiseAdmin.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<SysAdvertiseAdmin> selectByExampleWithoutBLOBs(SysAdvertiseAdminExample example) {
        List<SysAdvertiseAdmin> list = getSqlMapClientTemplate().queryForList("SysAdvertiseAdmin.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public SysAdvertiseAdmin selectByPrimaryKey(String adId) {
        SysAdvertiseAdmin key = new SysAdvertiseAdmin();
        key.setAdId(adId);
        SysAdvertiseAdmin record = (SysAdvertiseAdmin) getSqlMapClientTemplate().queryForObject("SysAdvertiseAdmin.selectByPrimaryKeyWithBLOBs", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByExampleSelective(SysAdvertiseAdmin record, SysAdvertiseAdminExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByExample(SysAdvertiseAdmin record, SysAdvertiseAdminExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByExampleWithoutBLOBs(SysAdvertiseAdmin record, SysAdvertiseAdminExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByPrimaryKeySelective(SysAdvertiseAdmin record) {
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByPrimaryKeyWithBLOBs(SysAdvertiseAdmin record) {
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_advertise_admin
     *
     * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
     */
    public int updateByPrimaryKeyWithoutBLOBs(SysAdvertiseAdmin record) {
        int rows = getSqlMapClientTemplate().update("SysAdvertiseAdmin.updateByPrimaryKey", record);
        return rows;
    }

    /**
    /**
     * <p>t_sys_advertise_admin查询条件参数。</p>
     */
    private static class UpdateByExampleParms extends SysAdvertiseAdminExample {
        private SysAdvertiseAdmin record;

        /**
         * <p>UpdateByExampleParms构造函数。</p>
         * @param record 实体
         * @param example 条件
         */
        public UpdateByExampleParms(SysAdvertiseAdmin record, SysAdvertiseAdminExample example) {
            super(example);
            this.record = record;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_advertise_admin
         *
         * @ibatorgenerated Mon Jun 12 15:55:41 CST 2017
         */
        @SuppressWarnings("unused")
        public SysAdvertiseAdmin getRecord() {
            return record;
        }
    }
}