package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.SysDictionary;
import com.yuguo.net.model.SysDictionaryExample;

public class SysDictionaryDAO extends GenericDAO<SysDictionary,SysDictionaryExample> implements ISysDictionaryDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public SysDictionaryDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int countByExample(SysDictionaryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SysDictionary.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int deleteByExample(SysDictionaryExample example) {
        int rows = getSqlMapClientTemplate().delete("SysDictionary.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int deleteByPrimaryKey(Long id) {
        SysDictionary key = new SysDictionary();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SysDictionary.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public void insert(SysDictionary record) {
        getSqlMapClientTemplate().insert("SysDictionary.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public void insertSelective(SysDictionary record) {
        getSqlMapClientTemplate().insert("SysDictionary.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<SysDictionary> selectByExample(SysDictionaryExample example) {
        List<SysDictionary> list = getSqlMapClientTemplate().queryForList("SysDictionary.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public SysDictionary selectByPrimaryKey(Long id) {
        SysDictionary key = new SysDictionary();
        key.setId(id);
        SysDictionary record = (SysDictionary) getSqlMapClientTemplate().queryForObject("SysDictionary.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int updateByExampleSelective(SysDictionary record, SysDictionaryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysDictionary.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int updateByExample(SysDictionary record, SysDictionaryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysDictionary.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int updateByPrimaryKeySelective(SysDictionary record) {
        int rows = getSqlMapClientTemplate().update("SysDictionary.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
     */
    public int updateByPrimaryKey(SysDictionary record) {
        int rows = getSqlMapClientTemplate().update("SysDictionary.updateByPrimaryKey", record);
        return rows;
    }

    /**
    /**
     * <p>t_sys_dictionary查询条件参数。</p>
     */
    private static class UpdateByExampleParms extends SysDictionaryExample {
        private SysDictionary record;

        /**
         * <p>UpdateByExampleParms构造函数。</p>
         * @param record 实体
         * @param example 条件
         */
        public UpdateByExampleParms(SysDictionary record, SysDictionaryExample example) {
            super(example);
            this.record = record;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_dictionary
         *
         * @ibatorgenerated Tue Apr 12 11:44:07 CST 2016
         */
        @SuppressWarnings("unused")
        public SysDictionary getRecord() {
            return record;
        }
    }
}