package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.SysPictureInfo;
import com.yuguo.net.model.SysPictureInfoExample;

public class SysPictureInfoDAO extends GenericDAO<SysPictureInfo,SysPictureInfoExample> implements ISysPictureInfoDAO{

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public SysPictureInfoDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int countByExample(SysPictureInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SysPictureInfo.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int deleteByExample(SysPictureInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("SysPictureInfo.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        SysPictureInfo key = new SysPictureInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("SysPictureInfo.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void insert(SysPictureInfo record) {
        getSqlMapClientTemplate().insert("SysPictureInfo.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public void insertSelective(SysPictureInfo record) {
        getSqlMapClientTemplate().insert("SysPictureInfo.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<SysPictureInfo> selectByExample(SysPictureInfoExample example) {
        List<SysPictureInfo> list = getSqlMapClientTemplate().queryForList("SysPictureInfo.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public SysPictureInfo selectByPrimaryKey(String id) {
        SysPictureInfo key = new SysPictureInfo();
        key.setId(id);
        SysPictureInfo record = (SysPictureInfo) getSqlMapClientTemplate().queryForObject("SysPictureInfo.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int updateByExampleSelective(SysPictureInfo record, SysPictureInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysPictureInfo.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int updateByExample(SysPictureInfo record, SysPictureInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SysPictureInfo.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int updateByPrimaryKeySelective(SysPictureInfo record) {
        int rows = getSqlMapClientTemplate().update("SysPictureInfo.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sys_picture_info
     *
     * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
     */
    public int updateByPrimaryKey(SysPictureInfo record) {
        int rows = getSqlMapClientTemplate().update("SysPictureInfo.updateByPrimaryKey", record);
        return rows;
    }

    /**
    /**
     * <p>t_sys_picture_info查询条件参数。</p>
     */
    private static class UpdateByExampleParms extends SysPictureInfoExample {
        private SysPictureInfo record;

        /**
         * <p>UpdateByExampleParms构造函数。</p>
         * @param record 实体
         * @param example 条件
         */
        public UpdateByExampleParms(SysPictureInfo record, SysPictureInfoExample example) {
            super(example);
            this.record = record;
        }

        /**
         * This method was generated by Apache iBATIS ibator.
         * This method corresponds to the database table t_sys_picture_info
         *
         * @ibatorgenerated Wed Nov 25 17:29:39 CST 2015
         */
        @SuppressWarnings("unused")
        public SysPictureInfo getRecord() {
            return record;
        }
    }
    
    
    public int updateByFileNameList(SysPictureInfo record,SysPictureInfoExample example) {
	  UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
      int rows = getSqlMapClientTemplate().update("SysPictureInfo.updateByFileNameList", parms);
      return rows;
    }
}