package com.yuguo.net.dao;

import java.util.List;

import com.yuguo.net.common.config.ibatis.GenericDAO;
import com.yuguo.net.model.TSysAdvertise;
import com.yuguo.net.model.TSysAdvertiseExample;

public class TSysAdvertiseDAO extends GenericDAO<TSysAdvertise, TSysAdvertiseExample> implements ITSysAdvertiseDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public TSysAdvertiseDAO() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int countByExample(TSysAdvertiseExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TSysAdvertise.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int deleteByExample(TSysAdvertiseExample example) {
		int rows = getSqlMapClientTemplate().delete("TSysAdvertise.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int deleteByPrimaryKey(String adId) {
		TSysAdvertise key = new TSysAdvertise();
		key.setAdId(adId);
		int rows = getSqlMapClientTemplate().delete("TSysAdvertise.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public void insert(TSysAdvertise record) {
		getSqlMapClientTemplate().insert("TSysAdvertise.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public void insertSelective(TSysAdvertise record) {
		getSqlMapClientTemplate().insert("TSysAdvertise.insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	@SuppressWarnings("unchecked")
	public List<TSysAdvertise> selectByExampleWithBLOBs(TSysAdvertiseExample example) {
		List<TSysAdvertise> list = getSqlMapClientTemplate().queryForList("TSysAdvertise.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	@SuppressWarnings("unchecked")
	public List<TSysAdvertise> selectByExampleWithoutBLOBs(TSysAdvertiseExample example) {
		List<TSysAdvertise> list = getSqlMapClientTemplate().queryForList("TSysAdvertise.selectByExampleWithoutBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public TSysAdvertise selectByPrimaryKey(String adId) {
		TSysAdvertise key = new TSysAdvertise();
		key.setAdId(adId);
		TSysAdvertise record = (TSysAdvertise) getSqlMapClientTemplate().queryForObject("TSysAdvertise.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByExampleSelective(TSysAdvertise record, TSysAdvertiseExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByExample(TSysAdvertise record, TSysAdvertiseExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByExampleWithoutBLOBs(TSysAdvertise record, TSysAdvertiseExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByExampleWithoutBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByPrimaryKeySelective(TSysAdvertise record) {
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByPrimaryKeyWithBLOBs(TSysAdvertise record) {
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_sys_advertise
	 * 
	 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
	 */
	public int updateByPrimaryKeyWithoutBLOBs(TSysAdvertise record) {
		int rows = getSqlMapClientTemplate().update("TSysAdvertise.updateByPrimaryKeyWithoutBLOBs", record);
		return rows;
	}

	/**
	 * /**
	 * <p>
	 * t_sys_advertise查询条件参数。
	 * </p>
	 */
	private static class UpdateByExampleParms extends TSysAdvertiseExample {
		private TSysAdvertise record;

		/**
		 * <p>
		 * UpdateByExampleParms构造函数。
		 * </p>
		 * 
		 * @param record
		 *            实体
		 * @param example
		 *            条件
		 */
		public UpdateByExampleParms(TSysAdvertise record, TSysAdvertiseExample example) {
			super(example);
			this.record = record;
		}

		/**
		 * This method was generated by Apache iBATIS ibator. This method
		 * corresponds to the database table t_sys_advertise
		 * 
		 * @ibatorgenerated Tue Dec 06 10:46:51 CST 2016
		 */
		@SuppressWarnings("unused")
		public TSysAdvertise getRecord() {
			return record;
		}
	}
}